MODULE_TOPDIR = ../..

PGM = r.categorize

GT_LIB_RAST = -lgt_raster
LIBES = $(GISLIB) $(DATETIMELIB) $(GT_LIB_RAST)
EXTRA_CFLAGS = -I../../include

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd
