MODULE_TOPDIR = ..

# i.fusion.brovey deprecated

SUBDIRS = \
	i.destripe \
	i.eb.deltat \
	i.eb.hsebal95 \
	i.eb.z0m \
	i.eb.z0m0 \
	i.edge \
	i.evapo.potrad \
	i.evapo.senay \
	i.evapo.zk \
	i.feotio2 \
	i.gcp \
	i.gravity \
	i.histo.match \
	i.in.probav \
	i.lmf \
	i.points.auto \
	i.rotate \
	i.segment.gsoc \
	i.segment.hierarchical \
	i.segment.stats \
	i.segment.uspo \
	i.spec.sam \
	i.spec.unmix \
	i.theilsen \
	i.vi.mpi \
	i.wavelet \
	i.water \
	i.wi

include $(MODULE_TOPDIR)/include/Make/Dir.make

default: subdirs
