MODULE_TOPDIR = ..

SUBDIRS = \
	i.eb.h_SEBAL95 \
	i.evapo.potrad \
	i.evapo.senay \
	i.evapo.zk \
	i.lmf \
	i.points.auto \
	i.vi.mpi

include $(MODULE_TOPDIR)/include/Make/Dir.make

default: subdirs
