MODULE_TOPDIR = ..

# i.fusion.brovey deprecated

SUBDIRS = \
	i.eb.h_sebal95 \
	i.edge \
	i.evapo.potrad \
	i.evapo.senay \
	i.evapo.zk \
	i.histo.match \
	i.lmf \
	i.points.auto \
	i.segment \
	i.vi.mpi

include $(MODULE_TOPDIR)/include/Make/Dir.make

default: subdirs
