MODULE_TOPDIR = ../..

SUBDIRS = \
	r.stream.order \
	r.stream.basins \
	r.stream.distance \
	r.stream.stats \
	r.stream.slope \
	r.stream.channel \
	r.stream.segment \
	r.stream.snap


include $(MODULE_TOPDIR)/include/Make/Dir.make

default: parsubdirs
