MODULE_TOPDIR = ../..

PGM = r.seg

LIBES = $(SEGLIB) $(GISLIB)
DEPENDENCIES = $(SEGDEP) $(GISDEP)

include $(MODULE_TOPDIR)/include/Make/Module.make
include $(MODULE_TOPDIR)/include/Make/Doxygen.make

default: cmd

#doxygen:
DOXNAME = r.seg
