MODULE_TOPDIR = ../..

include $(MODULE_TOPDIR)/include/Make/Dir.make

SUBDIRS = \
        PRLIB \
	i.pr.blob \
	i.pr.classify \
	i.pr.features \
	i.pr.features_additional \
	i.pr.features_extract \
	i.pr.features_selection \
	i.pr.model \
	i.pr.statistics \
	i.pr.subsets \
	i.pr.training \
	i.pr.uxb \
	i.pr.sites_aggregate

default: subdirs

clean: cleansubdirs

install: installsubdirs
