MODULE_TOPDIR = ../../..

PGM = r.stream.distance

LIBES = $(GISLIB) $(RASTERLIB) $(SEGMENTLIB)
DEPENDENCIES = $(GISDEP) $(RASTERDEP) $(SEGMENTDEP) $(VECTDEP)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd

