MODULE_TOPDIR = ../..

PGM = r.prominence

GTLIB = -lgt
LIBES = $(RASTERLIB) $(GISLIB) $(DATETIMELIB)
DEPENDENCIES = $(RASTERDEP) $(GISDEP)
#EXTRA_CFLAGS = -I../dst/include \     

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd
