MODULE_TOPDIR = ../..

PGM = i.linespoints



LIBES     = $(IMAGERYLIB) $(GMATHLIB) $(D_LIB) $(DISPLAYLIB) $(GISLIB) $(VASKLIB) $(CURSES) $(FFTWLIB)
DEPENDENCIES= $(IMAGERYDEP) $(GMATHDEP) $(D_DEP) $(DISPLAYDEP) $(GISDEP) $(VASKDEP)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd
