MODULE_TOPDIR = ../..

PGM = v.random.sample

GT_LIB_RAST = -lgt_raster
LIBES = $(GISLIB) $(DATETIMELIB) $(VECTLIB) $(GT_LIB_RAST)
EXTRA_CFLAGS = -I../../include

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd
