# Uncoment and fix MODULE_TOPDIR line OR provide MODULE_TOPDIR variable for make
# fix this relative to include/
# or use absolute path to the GRASS source code
#MODULE_TOPDIR = ../..

PGM = r.traveltime

LIBES = $(GISLIB)
DEPENDENCIES = $(GISDEP)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd
