MODULE_TOPDIR = ../..

PGM = v.in.wfs2

ETCFILES = wfs_base wfs_drv wfs_owslib_drv

include $(MODULE_TOPDIR)/include/Make/Script.make
include $(MODULE_TOPDIR)/include/Make/Python.make

default: script
