MODULE_TOPDIR = ..

SUBDIRS = \
	g.cloud \
	g.compare.md5 \
	g.copyall \
	g.download.location \
	g.isis3mt \
	g.proj.all \
	g.rename.many

include $(MODULE_TOPDIR)/include/Make/Dir.make

default: subdirs
