MODULE_TOPDIR = ..

SUBDIRS = \
        r.categorize \
	r.dst.combine \
	r.dst.predict.bpn \
	r.dst.predict.run

include $(MODULE_TOPDIR)/include/Make/Dir.make

default: htmldir

htmldir: subdirs

clean: cleansubdirs
