MODULE_TOPDIR = ../../..

PGM = r.watershed.seg.fast

LIBES = $(GISLIB) $(SEGMENTLIB)
DEPENDENCIES = $(GISDEP) $(SEGMENTDEP)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: etc

htmletc:
	@echo "No docs to generate."
