MODULE_TOPDIR = ..

SUBDIRS = \
	r.evapo.MH \
	r.evapo.PM \
	r.gaswap.serial \
	r.hydro.CASC2D \
	r.inund.fluv \
	r.out.vic \
	r.soilusda2tex \
	r.soiltex2prop \
	r.usler 

include $(MODULE_TOPDIR)/include/Make/Platform.make

PGM = rasterintro

include $(MODULE_TOPDIR)/include/Make/Dir.make

default: htmldir

htmldir: parsubdirs 

clean: cleansubdirs
