class Data:
    '''Data object that returns menu descriptions to be used in wxgui.py.
    Probably could be changed to XML or *.dtd file.'''
    def GetMenu(self):
        return [(
          ("Files", (
             ("Import", (
                 ("Raster map", (
                     ("Multiple formats using GDAL", "Import multiple formats using GDAL", "self.OnMenuCmd", "r.in.gdal"),
                     ("","","", ""),
                     ("Aggregate ASCII xyz", "Import aggregate ASCII xyz data", "self.OnMenuCmd", "r.in.xyz"),
                     ("ASCII grid", "Import ASCII GRID (includes GRASS ASCII)", "self.OnMenuCmd", "r.in.ascii"),
                     ("ASCII polygons and lines", "Import Polygons and lines from ASCII file", "self.OnMenuCmd", "r.in.poly"),
                     ("","","", ""),
                     ("Binary", "Import binary file (includes GTOPO30 format)", "self.OnMenuCmd", "r.in.bin"),
                     ("ESRI Arc/Info ASCII grid", "Import ESRI Arc/Info ASCII grid", "self.OnMenuCmd", "r.in.arc"),
                     ("GRIDATB.FOR", "Import GRIDATB.FOR map file (TOPMODEL)", "self.OnMenuCmd", "r.in.gridatb"),
                     ("MAT-File (v.4)", "Import MAT-File (v.4) array (Matlab or Octave)", "self.OnMenuCmd", "r.in.mat"),
                     ("SPOT NDVI", "Import SPOT vegetation NDVI data sets", "self.OnMenuCmd", "r.in.spotvgt"),
                     ("SRTM HGT", "Import SRTM hgt files", "self.OnMenuCmd", "r.in.srtm"),
                     ("Terra ASTER HDF", "Import Terra ASTER HDF files", "self.OnMenuCmd", "r.in.aster"),
                     ("","","", ""),
                     ("WMS", "Import Web Mapping Server", "self.OnMenuCmd", "r.in.wms"),
                     )),
                 ("Vector map", (
                     ("Multiple formats using OGR", "Import multiple formats using OGR", "self.OnMenuCmd", "v.in.ogr"),
                     ("","","", ""),
                     ("ASCII points or GRASS ASCII vector", "Import ASCII points file or GRASS ASCII vector file", "self.OnMenuCmd", "v.in.ascii"),
                     ("Old GRASS vector", "Import old GRASS vector format", "self.OnMenuCmd", "v.convert"),
                     ("","","", ""),
                     ("DXF", "Import DXF file", "self.OnMenuCmd", "v.in.dxf"),
                     ("ESRI e00", "Import ESRI e00 file", "self.OnMenuCmd", "v.in.e00"),
                     ("Garmin GPS", "Import Garmin GPS Waypoints/Routes/Tracks", "self.OnMenuCmd", "v.in.garmin"),
                     ("GPSBabel GPS", "Import GPS Waypoints/Routes/Tracks using GPSBabel", "self.OnMenuCmd", "v.in.gpsbabel"),
                     ("GEOnet", "Import GEOnet Name server country files (US-NGA GNS)", "self.OnMenuCmd", "v.in.gns"),
                     ("Matlab and MapGen", "Import Matlab and MapGen files", "self.OnMenuCmd", "v.in.mapgen"),
                     )),

                 ("Grid 3D", (
                     ("ASCII 3D", "Import ASCII 3D file", "self.OnMenuCmd", "r3.in.ascii"),
                     ("Vis5D", "Import Vis5D file", "self.OnMenuCmd", "r3.in.v5d"),
                     )),
                 )),
              ("Export", (
                 ("Raster map", (
                     ("Multiple formats using GDAL", "Export multiple formats using GDAL", "self.OnMenuCmd", "r.out.gdal"),
                     ("","","", ""),
                     ("ASCII grid", "Export ASCII grid (for GRASS, Surfer, Modflow, etc)", "self.OnMenuCmd", "r.out.ascii"),
                     ("ASCII x,y,z", "Export ASCII x,y,z values of cell centers", "self.OnMenuCmd", "r.out.xyz"),
                     ("","","", ""),
                     ("ESRI ASCII grid", "Export ESRI Arc/Info ASCII grid", "self.OnMenuCmd", "r.out.arc"),
                     ("GRIDATB.FOR", "Export GRIDATB.FOR map file (TOPMODEL)", "self.OnMenuCmd", "r.out.gridatb"),
                     ("MAT-File (v.4)", "Export MAT-File (v.4) array (Matlab or Octave)", "self.OnMenuCmd", "r.out.mat"),
                     ("","","", ""),
                     ("Binary", "Export binary file", "self.OnMenuCmd", "r.out.bin"),
                     ("","","", ""),
                     ("MPEG-1", "Export MPEG-1 animations", "self.OnMenuCmd", "r.out.mpeg"),
                     ("PNG", "Export PNG image (not georeferenced)", "self.OnMenuCmd", "r.out.png"),
                     ("PPM", "Export PPM image (24bit)", "self.OnMenuCmd", "r.out.ppm"),
                     ("POV-Ray", "Export POVray height-field", "self.OnMenuCmd", "r.out.pov"),
                     ("TIFF", "Export TIFF image (8/24bit)", "self.OnMenuCmd", "r.out.tiff"),
                     ("VRML", "Export VRML file", "self.OnMenuCmd", "r.out.vrml"),
                     ("VTK", "Export VTK ASCII file", "self.OnMenuCmd", "r.out.vtk"),
                     )),
                 ("Vector map", (
                     ("Multiple formats using OGR", "Export multiple formats using OGR", "self.OnMenuCmd", "v.out.ogr"),
                     ("","","", ""),
                     ("ASCII points or GRASS ASCII vector", "Import ASCII points file or GRASS ASCII vector file", "self.OnMenuCmd", "v.out.ascii"),

                     ("DXF", "Export DXF file", "self.OnMenuCmd", "v.out.dxf"),
                     ("POV-Ray", "Export POV-Ray format file", "self.OnMenuCmd", "v.out.pov"),
                     ("SVG", "Export SVG file", "self.OnMenuCmd", "v.out.svg"),
                     ("VTK", "Export VTK ASCII file", "self.OnMenuCmd", "v.out.vtk"),
                     )),

                 ("Grid 3D", (
                     ("ASCII 3D", "Export ASCII 3D file", "self.OnMenuCmd", "r3.out.ascii"),
                     ("Vis5D", "Export Vis5D file", "self.OnMenuCmd", "r3.out.v5d"),
                     ("VTK", "Export VTK ASCII file", "self.OnMenuCmd", "r3.out.vtk"),
                     )),
                 )),
              ("","","", ""),
              ("Manage maps and volumes", (
                ("Copy", "Copy maps within mapsets or between mapsets", "self.OnMenuCmd", "g.copy"),
                ("","","", ""),
                ("List", "List maps by type", "self.OnMenuCmd", "list"),
                ("List filtered", "List maps filtered by expressions and wildcards", "self.OnMenuCmd", "g.mlist"),
                ("","","", ""),
                ("Rename", "Rename maps", "self.OnMenuCmd", "g.rename"),
                ("","","", ""),
                ("Delete", "Delete maps", "self.OnMenuCmd", "g.remove"),
                ("Delete filtered", "Delete maps using expressions and wildcards", "self.OnMenuCmd", "g.mremove"),
                )),
              ("Map type conversions", (
                ("Raster to vector", "Convert raster to vector map", "self.OnMenuCmd", "r.to.vect"),
                ("Raster series to volume", "Convert raster map series to volume", "self.OnMenuCmd", "r.to.rast3"),
                ("Raster 2.5D to volume", "Convert raster 2.5D map to volume", "self.OnMenuCmd", "r.to.rast3elev"),
                ("","","", ""),
                ("Vector to raster", "Convert vector to raster map", "self.OnMenuCmd", "v.to.rast"),
                ("Vector to volume", "Convert vector 3D points to volume voxels", "self.OnMenuCmd", "v.to.rast3"),
                ("Sites to vector", "Convert sites (GRASS 5) to vector map", "self.OnMenuCmd", "v.in.sites"),
                ("","","", ""),
                ("Volumes to raster series", "Convert raster to vector map", "self.OnMenuCmd", "r3.to.rast"),
                )),
              ("","","", ""),
              ("Georectify (not functional)", "Georectify raster and vector maps", "self.OnGeorectify", ""),
              ("","","", ""),
              ("Bearing/distance to coordinates", "Convert between bearing/distance and coordinates", "self.OnMenuCmd", "m.cogo"),
              ("","","", ""),
              ("Postscript plot", "Create cartographic PostScript plot", "self.OnMenuCmd", "ps.map"),
              ("","","", ""),
              ("E&xit", "Exit from wxgui.py", "self.OnCloseWindow", ""),
              )),
          ("Config", (
              ("Region", (
                ("Display region", "Display region settings", "self.RunMenuCmd", "g.region -p"),
                ("Set region", "Change region settings", "self.OnMenuCmd", "g.region"),
              )),
              ("GRASS working environment", (
                ("Mapset access (not functional)", "Set access to other mapsets in current location", "self.OnMapsets", ""),
                ("Change working environment", "Change current working session to new mapset, location, or data directory", "self.OnMenuCmd", "g.mapset"),
                ("User access", "Change access by other users to current mapset", "self.OnMenuCmd", "g.access"),
                ("Show settings", "Show current GRASS environment settings", "self.RunMenuCmd", "g.gisenv "),
                ("Change settings", "Change GRASS environment settings", "self.OnMenuCmd", "g.gisenv"),
                ("Version", "Show current GRASS version", "self.RunMenuCmd", "g.version -c"),
              )),
              ("Manage projections", (
                ("Projections", "Show projection information and create projection files", "self.OnMenuCmd", "g.proj"),
                ("Convert coordinates", "Convert coordinates from one projection to another", "self.OnMenuCmd", "m.proj"),
              )),
              ("Display font", "Set default font for GRASS displays", "self.DefaultFont", ""),
              )),
          ("Raster", (
              ("Develop map", (
                ("Digitize raster (not functional)", "Digitize raster", "self.OnRDigit", ""),
                ("","","", ""),
                ("Compress/decompress raster file", "Compress/decompress raster file", "self.OnMenuCmd", "r.compress"),
                ("Manage boundary definition (WHICH COMMAND?)", "Manage boundary definition", "self.OnMenuCmd", "r.region"),
                ("Manage null values", "Manage null values", "self.OnMenuCmd", "r.null"),
                ("Manage timestamp for files", "Manage timestamp for files", "self.OnMenuCmd", "r.timestamp"),
                ("Quantization for floating-point maps", "Quantization for floating-point maps", "self.OnMenuCmd", "r.quant"),
                ("Resample (change resolution) using nearest neighbor method", "Resample (change resolution) using nearest neighbor method", "self.OnMenuCmd", "r.resample"),
                ("Resample (change resolution) using regularized spline tension", "Resample (change resolution) using regularized spline tension", "self.OnMenuCmd", "r.resamp.rst"),
                ("Support file creation and maintenance", "Support file creation and maintenance", "self.OnMenuCmd", "r.support.sh"),
                ("","","", ""),
                ("Reproject raster from other location", "Reproject raster from other location", "self.OnMenuCmd", "r.proj"),
                ("Generate tiling for other projection", "Generate tiling for other projection", "self.OnMenuCmd", "r.tileset"),
                )),
              ("Manage map colors", (
                ("Set colors to predefined color tables", "Set colors to predefined color tables", "self.OnMenuCmd", "r.colors"),
                ("Set colors using color rules", "Set colors using color rules", "self.OnMenuCmd", "r.colors.rules"),
                ("","","", ""),
                ("Blend 2 color maps to produce 3 RGB files", "Blend 2 color maps to produce 3 RGB files", "self.OnMenuCmd", "r.blend"),
                ("Create color image from RGB files", "Create color image from RGB files", "self.OnMenuCmd", "r.composite"),
                ("Create 3 RGB (red, green, blue) maps from 3 HIS (hue, intensity, saturation) maps", "Create 3 RGB (red, green, blue) maps from 3 HIS (hue, intensity, saturation) maps", "self.OnMenuCmd", "r.his"),
                )),
              ("Query/Profile", (
                ("Query by coordinates", "Query by coordinates", "self.OnMenuCmd", "r.what"),
                ("Profile", "Profile of transect", "self.DispProfile", ""),
                )),
              ("","","", ""),
              ("Create raster MASK", "Develop raster mask", "self.OnMenuCmd", "r.mask"),
              ("Create raster buffers", "Develop raster buffer", "self.OnMenuCmd", "r.buffer"),
              ("Map calculator", "Map calculator", "self.OnMenuCmd", "scripts/mapcalc_gparser.sh"),
              ("","","", ""),
              ("Overlay maps", (
                ("Cross product", "Cross product", "self.OnMenuCmd", "r.cross"),
                ("Function of map series (time series)", "Function of map series (time series)", "self.OnMenuCmd", "r.series"),
                ("Patch maps", "Patch maps", "self.OnMenuCmd", "r.patch"),
                ("","","", ""),
                ("Statistical calculations for cover map over base map", "Statistical calculations for cover map over base map", "self.OnMenuCmd", "r.statistics"),
                )),
              ("Transform features", (
                ("Clump small areas (statistics calculated by r.volume)", "Clump small areas (statistics calculated by r.volume)", "self.OnMenuCmd", "r.clump"),
                ("Grow areas", "Grow areas", "self.OnMenuCmd", "r.grow"),
                ("Thin linear features", "Thin linear features", "self.OnMenuCmd", "r.thin"),
                )),
              ("Proximity/Neighborhood analysis", (
                ("Moving window analysis of raster cells", "Moving window analysis of raster cells", "self.OnMenuCmd", "r.neighbors"),
                ("Analyze vector points in neighborhood of raster cells", "Analyze vector points in neighborhood of raster cells", "self.OnMenuCmd", "v.neighbors"),
                ("","","", ""),
                ("Locate closest points between areas in 2 raster maps", "r.distance", "self.OnMenuCmd", "r.distance"),
                )),
              ("","","", ""),
              ("Modeling: Hydrologic", (
                ("Carve stream channels into elevation map using vector streams map", "Carve stream channels into elevation map using vector streams map", "self.OnMenuCmd", "r.carve"),
                ("Depressionless elevation map and flowline map", "Depressionless elevation map and flowline map", "self.OnMenuCmd", "r.fill.dir"),
                ("Fill lake from seed point to specified level", "Fill lake from seed point to specified level", "self.OnMenuCmd", "r.lake"),
                ("Flow accumulation for massive grids (WHICH COMMAND?)", "Flow accumulation for massive grids", "self.OnMenuCmd", "r.flow"),
                ("Generate flow lines for raster map (WHICH COMMAND?)", "Generate flow lines for raster map", "self.OnMenuCmd", "r.flow"),
                ("SIMWE overland flow modeling (WHICH COMMAND?)", "SIMWE overland flow modeling", "self.OnMenuCmd", "r.simwe"),
                ("SIMWE sediment erosion, transport, deposition modeling (WHICH COMMAND?)", "SIMWE sediment erosion, transport, deposition modeling", "self.OnMenuCmd", "r.simwe"),
                ("Topographic index map", "Topographic index map", "self.OnMenuCmd", "r.topidx"),
                ("TOPMODEL simulation", "TOPMODEL simulation", "self.OnMenuCmd", "r.topmodel"),
                ("Watershed subbasins", "Watershed subbasins", "self.OnMenuCmd", "r.basins.fill"),
                ("Watershed analysis", "Watershed analysis", "self.OnMenuCmd", "r.watershed"),
                ("Watershed basin creation", "Watershed basin creation", "self.OnMenuCmd", "r.water.outlet"),
                )),
              ("Modeling: Landscape structure", (
                ("Set up sampling and analysis framework", "Set up sampling and analysis framework", "self.OnMenuCmd", "r.le.setup"),
                ("","","", ""),
                ("Analyze landscape characteristics", "Analyze landscape characteristics", "self.OnMenuCmd", "r.le.pixel"),
                ("Analyze landscape patch characteristics", "Analyze landscape patch characteristics", "self.OnMenuCmd", "r.le.patch"),
                ("Output landscape patch information", "Output landscape patch information", "self.OnMenuCmd", "r.le.trace"),
                )),
              ("Modeling: Landscape patch analysis", (
                ("Configure and create patch map for analysis", "Configure and create patch map for analysis", "self.RunMenuCmd", "r.li.setup"),
                ("","","", ""),
                ("Contrast weighted edge density index", "Calculate contrast weighted edge density index",  "self.RunMenuCmd", "r.li.cwed"),
                ("Calculate dominance's diversity index", "Calculate dominance's diversity index",  "self.RunMenuCmd", "r.li.dominance"),
                ("Edge density index using a 4 neighbour algorithm","Calculate edge density index using a 4 neighbour algorithm", "self.RunMenuCmd",  "r.li.edgedensity"),
                ("Mean patch size index using a 4 neighbour algorithm", "Calculate mean patch size index using a 4 neighbour algorithm",  "self.RunMenuCmd", " r.li.mps"),
                ("Coefficient of variation of patch area","Calculate coefficient of variation of patch area",  "self.RunMenuCmd", "r.li.padcv"),
                ("Range of patch area size", "Calculate range of patch area size",  "self.RunMenuCmd", "r.li.padrange"),
                ("Standard deviation of patch area","Calculate standard deviation of patch area",  "self.RunMenuCmd", "r.li.padsd"),
                ("Patch density index using a 4 neighbour algorithm","Calculate patch density index using a 4 neighbour algorithm",  "self.RunMenuCmd", "r.li.patchdensity"),
                ("Patch number index using a 4 neighbour algorithm", "Calculate patch number index using a 4 neighbour algorithm",  "self.RunMenuCmd", "r.li.patchnum"),
                ("Dominance's diversity index", "Calculate dominance's diversity index",  "self.RunMenuCmd", "r.li.shannon"),
                ("Shannon's diversity index", "Calculate Shannon's diversity index",  "self.RunMenuCmd", "r.li.richness"),
                ("Shape index", "Calculate shape index",  "self.RunMenuCmd", "r.li.shape"),
                ("Simpson's diversity index", "Calculate Simpson's diversity index",  "self.RunMenuCmd", "r.li.simpson"),
                )),
              ("Modeling: Terrain and Solar", (
                ("Calculate cumulative movement costs between locales", "Calculate cumulative movement costs between locales", "self.OnMenuCmd", "r.walk"),
                ("cost surface", "cost surface", "self.OnMenuCmd", "r.cost"),
                ("Least cost route or flow", "Least cost route or flow", "self.OnMenuCmd", "r.drain"),
                ("","","", ""),
                ("Shaded relief map", "Shaded relief map", "self.OnMenuCmd", "r.shaded.relief"),
                ("Slope and aspect", "Slope and aspect", "self.OnMenuCmd", "r.slope.aspect"),
                ("Terrain parameters", "Terrain parameters", "self.OnMenuCmd", "r.param.scale"),
                ("","","", ""),
                ("Textural features", "Textural features", "self.OnMenuCmd", "r.texture"),
                ("Visibility/Line of sight", "Visibility/Line of sight", "self.OnMenuCmd", "r.los"),
                ("","","", ""),
                ("Solar irradiance and daily irradiation", "Solar irradiance and daily irradiation", "self.OnMenuCmd", "r.sun"),
                ("Shadow map for sun position or date/time", "Shadow map for sun position or date/time", "self.OnMenuCmd", "r.sunmask"),
                )),
              ("Modeling: Wildfire", (
                ("Generate rate of spread (ROS) maps", "Generate rate of spread (ROS) maps", "self.OnMenuCmd", "r.ros"),
                ("Generate least-cost spread paths", "Generate least-cost spread paths", "self.OnMenuCmd", "r.spreadpath"),
                ("Simulate anisotropic spread phenomena", "Simulate anisotropic spread phenomena", "self.OnMenuCmd", "r.spread"),
                )),
              ("","","", ""),
              ("Change category values and labels", (
                ("Edit category values of individual cells for displayed raster map", "Edit category values of individual cells for displayed raster map", "self.OnMenuCmd", "d.rast.edit"),
                ("","","", ""),
                ("Reclassify categories for areas of specified sizes", "Reclassify categories for areas of specified sizes", "self.OnMenuCmd", "r.reclass.area"),
                ("Reclassify categories using rules", "Reclassify categories using rules", "self.OnMenuCmd", "r.reclass.rules"),
                ("Reclassify categories using rules file", "Reclassify categories using rules file", "self.OnMenuCmd", "r.reclass.file"),
                ("","","", ""),
                ("Recode categories using rules (create new map)", "Recode categories using rules (create new map)", "self.OnMenuCmd", "r.recode.rules"),
                ("Recode categories using rules file (create new map)", "Recode categories using rules file (create new map)", "self.OnMenuCmd", "r.recode.file"),
                ("","","", ""),
                ("Rescale categories (create new map)", "Rescale categories (create new map)", "self.OnMenuCmd", "r.rescale"),
                ("Rescale categories with equalized histogram (create new map)", "Rescale categories with equalized histogram (create new map)", "self.OnMenuCmd", "r.rescale.eq"),
                )),
              ("","","", ""),
              ("Generate", (
                ("Concentric circles around points", "Generate concentric circles around points", "self.OnMenuCmd", "r.circle"),
                ("Density surface using moving Gaussian kernel", "Generate density surface using moving Gaussian kernel", "self.OnMenuCmd", "v.kernel"),
                ("Fractal surface", "Generate fractal surface", "self.OnMenuCmd", "r.surf.fractal"),
                ("Gaussian deviates surface", "Generate gaussian deviates surface", "self.OnMenuCmd", "r.surf.gauss"),
                ("Generate plane", "Generate plane", "self.OnMenuCmd", "r.plane"),
                ("","","", ""),
                ("Random cells", "Generate random cells", "self.OnMenuCmd", "r.random.cells"),
                ("Random cells and vector points from raster map", "Generate random cells and vector points from raster map", "self.OnMenuCmd", "r.random"),
                ("Random deviates surface", "Generate random deviates surface", "self.OnMenuCmd", "r.surf.random"),
                ("Random surface with spatial dependence", "Generate random surface with spatial dependence", "self.OnMenuCmd", "r.random.surface"),
                ("","","", ""),
                ("Generate vector contour lines", "Generate vector contour lines", "self.OnMenuCmd", "r.contour"),
                )),
	      ("Interpolate surfaces", (
                ("Bilinear interpolation from raster points", "Bilinear interpolation from raster points", "self.OnMenuCmd", "r.bilinear"),
                ("Inverse distance weighted interpolation from raster points", "Inverse distance weighted interpolation from raster points", "self.OnMenuCmd", "r.surf.idw"),
                ("Interpolation from raster contour", "Interpolation from raster contour", "self.OnMenuCmd", "r.surf.contour"),
                ("","","", ""),
                ("Inverse distance weighted interpolation from vector points", "Inverse distance weighted interpolation from vector points", "self.OnMenuCmd", "v.surf.idw"),
                ("Regularized spline tension interpolation from vector points or contours (WHICH COMMAND ?)", "Regularized spline tension interpolation from vector points or contours", "self.OnMenuCmd", "v.surf.rst"),
                ("","","", ""),
                ("Fill NULL cells by interpolation using regularized spline tension", "Fill NULL cells by interpolation using regularized spline tension", "self.OnMenuCmd", "r.fillnulls"),
                )),
              ("","","", ""),
              ("Report and statistics", (
                ("Report basic file information", "Report basic file information", "self.OnMenuCmd", "r.info"),
                ("Report category labels and values", "Report category labels and values", "self.OnMenuCmd", "r.cats"),
                ("","","", ""),
                ("General statistics", "General statistics", "self.OnMenuCmd", "r.stats"),
                ("Range of all category values", "Range of all category values", "self.OnMenuCmd", "r.describe"),
                ("Sum all cell category values", "Sum all cell category values", "self.OnMenuCmd", "r.sum"),
                ("Sum area by map and category", "Sum area by map and category", "self.OnMenuCmd", "r.report"),
                ("Summary statistics for clumped cells (work with r.clump)", "Summary statistics for clumped cells (work with r.clump)", "self.OnMenuCmd", "r.volume"),
                ("Total surface area corrected for topography", "Total surface area corrected for topography", "self.OnMenuCmd", "r.surf.area"),
                ("Univariate statistics", "Univariate statistics", "self.OnMenuCmd", "r.univar"),
                ("Univariate statistics (script version)", "Univariate statistics (script version)", "self.OnMenuCmd", "r.univar.sh"),
                ("","","", ""),
                ("Sample values along transects", "Sample values along transects", "self.OnMenuCmd", "r.profile"),
                ("Sample values along transects (use azimuth, distance)", "Sample values along transects (use azimuth, distance)", "self.OnMenuCmd", "r.transect"),
                ("","","", ""),
                ("Covariance/correlation", "Covariance/correlation", "self.OnMenuCmd", "r.covar"),
                ("Linear regression between 2 maps", "Linear regression between 2 maps", "self.OnMenuCmd", "r.regression.line"),
                ("Mutual category occurrences (coincidence)", "Mutual category occurrences (coincidence)", "self.OnMenuCmd", "r.coin"),
                )),
              ("","","", "")
              )),
          ("Vector", (
              ("Develop map", (
                ("Digitize", "Digitize vector", "self.OnMenuCmd", "v.digit"),
                ("","","", ""),
                ("Create/Rebuild topology", "Create/Rebuild topology", "self.OnMenuCmd", "v.build"),
                ("Clean vector files", "clean vector files", "self.OnMenuCmd", "v.clean"),
                ("","","", ""),
                ("Break lines at intersections", "Break lines at intersections", "self.OnMenuCmd", "v.topo.check"),
                ("Build polylines from adjacent segments", "Build polylines from adjacent segments", "self.OnMenuCmd", "v.build.polylines"),
                ("Split polylines into segments", "Split polylines into segments", "self.OnMenuCmd", "v.segment"),
                ("Create lines parallel to existing lines", "Create lines parallel to existing lines", "self.OnMenuCmd", "v.parallel"),
                ("","","", ""),
                ("Convert vector feature types", "Convert vector feature types", "self.OnMenuCmd", "v.type"),
                ("Convert 2D vector to 3D by sampling raster", "Convert 2D vector to 3D by sampling raster", "self.OnMenuCmd", "v.drape"),
                ("Extrude 2D vector into 3D vector", "Extrude 2D vector into 3D vector", "self.OnMenuCmd", "v.extrude"),
                ("","","", ""),
                ("Create text label file for vector features", "Create text label file for vector features", "self.OnMenuCmd", "v.label"),
                ("","","", ""),
                ("Reproject vector from other location", "Reproject vector from other location", "self.OnMenuCmd", "v.proj"),
                ("","","", "")
                )),
              ("","","", ""),
              ("vector<->database connections", (
                ("Create new vector as link to external OGR layer", "Create new vector as link to external OGR layer", "self.OnMenuCmd", "v.external"),
                ("Set database connection for vector attributes", "Set database connection for vector attributes", "self.OnMenuCmd", "v.db.connect"),
                )),
              ("Query by attributes", "Query by attributes", "self.OnMenuCmd", "v.extract"),
              ("Query by coordinate(s)", "Query by coordinate(s)", "self.OnMenuCmd", "v.what"),
              ("Query by map features", "Query by map features", "self.OnMenuCmd", "v.select"),
              ("","","", ""),
              ("Create vector buffers", "Create vector buffers", "self.OnMenuCmd", "v.buffer"),
              ("Linear referencing for vectors", (
                ("Create linear reference system", "Create linear reference system", "self.OnMenuCmd", "v.lrs.create"),
                ("Create stationing from input lines, and linear reference system", "Create stationing from input lines, and linear reference system", "self.OnMenuCmd", "v.lrs.label"),
                ("Create points/segments from input lines, linear reference system and positions read from stdin", "Create points/segments from input lines, linear reference system and positions read from stdin", "self.OnMenuCmd", "v.lrs.segment"),
                ("Find line id and real km+offset for given points in vector map using linear reference system", "Find line id and real km+offset for given points in vector map using linear reference system", "self.OnMenuCmd", "v.lrs.where"),
                )),
              ("Neighborhood analysis", (
                ("Locate nearest feature to points or centroids", "Locate nearest feature to points or centroids", "self.OnMenuCmd", "v.distance"),
                ("Generate Thiessen polygons around points (Voronoi diagram)", "Generate Thiessen polygons around points (Voronoi diagram)", "self.OnMenuCmd", "v.voronoi"),
                ("Connect points to create Delaunay triangles", "Connect points to create Delaunay triangles", "self.OnMenuCmd", "v.delaunay"),
                )),
              ("Network analysis", (
                ("Allocate subnets", "Allocate subnets", "self.OnMenuCmd", "v.net.alloc"),
                ("Network maintenance", "Network maintenance", "self.OnMenuCmd", "v.net"),
                ("Shortest route", "Shortest route", "self.OnMenuCmd", "v.net.path"),
                ("Shortest route (visualization only)", "Shortest route (visualization only)", "self.OnMenuCmd", "d.path"),
                ("Split net to bands between cost isolines", "Split net to bands between cost isolines", "self.OnMenuCmd", "v.net.iso"),
                ("Steiner tree", "Steiner tree", "self.OnMenuCmd", "v.net.steiner"),
                ("Traveling salesman analysis", "Traveling salesman analysis", "self.OnMenuCmd", "v.net.salesman"),
                )),
              ("Overlay maps", (
                ("Overlay/combine 2 vector maps", "Overlay/combine 2 vector maps", "self.OnMenuCmd", "v.overlay"),
                ("Patch multiple maps (combine)", "Patch multiple maps (combine)", "self.OnMenuCmd", "v.patch"),
                )),
              ("Generate area feature for extent of current region", "Generate area feature for extent of current region", "self.OnMenuCmd", "v.in.region"),
              ("Generate rectangular vector grid", "Generate rectangular vector grid", "self.OnMenuCmd", "v.mkgrid"),
              ("","","", ""),
              ("Change attributes", (
                ("Attach/delete, or report categories", "Attach/delete, or report categories", "self.OnMenuCmd", "v.category"),
                ("Reclassify features using rules file", "Reclassify features using rules file", "self.OnMenuCmd", "v.reclass"),
                )),
              ("","","", ""),
              ("Work with vector points", (
                ("Generate points", (
                    ("Generate points from database", "Generate points from database", "self.OnMenuCmd", "v.in.db"),
                    ("Generate random points", "Generate random points", "self.OnMenuCmd", "v.random"),
                    ("Random location perturbations of points", "Random location perturbations of points", "self.OnMenuCmd", "v.perturb"),
                    )),
                ("Generate areas from points", (
                    ("Generate convex hull for point set", "Generate convex hull for point set", "self.OnMenuCmd", "v.hull"),
                    ("Generate Delaunay triangles for point set", "Generate Delaunay triangles for point set", "self.OnMenuCmd", "v.delaunay"),
                    ("Generate Voronoi diagram/Thiessen polygons for point set", "Generate Voronoi diagram/Thiessen polygons for point set", "self.OnMenuCmd", "v.voronoi"),
                    )),
                ("Sample raster maps", (
                    ("Calculate statistics for raster map overlain by vector map", "Calculate statistics for raster map overlain by vector map", "self.OnMenuCmd", "v.rast.stats"),
                    ("Sample raster maps at point locations", "Sample raster maps at point locations", "self.OnMenuCmd", "v.what.rast"),
                    ("Sample raster neighborhood around points", "Sample raster neighborhood around points", "self.OnMenuCmd", "v.sample"),
                    )),
                ("Partition points into test/training sets for k-fold cross validation", "Partition points into test/training sets for k-fold cross validation", "self.OnMenuCmd", "v.kcv"),
                ("Transfer attribute data from queried vector map to points", "Transfer attribute data from queried vector map to points", "self.OnMenuCmd", "v.what.vect"),
                )),
              ("","","", ""),
              ("Reports and statistics", (
                ("Basic information", "Basic information", "self.OnMenuCmd", "v.info"),
                ("Load vector attributes to database or create reports", "Load vector attributes to database or create reports", "self.OnMenuCmd", "v.to.db"),
                ("Report areas for vector attribute categories", "Report areas for vector attribute categories", "self.OnMenuCmd", "v.report"),
                ("Univariate statistics", "Univariate statistics", "self.OnMenuCmd", "v.univar"),
                ("","","", ""),
                ("Test normality of point distribution", "Test normality of point distribution", "self.OnMenuCmd", "v.normal"),
                ("Calculate stats for raster map underlying vector objects", "Calculate stats for raster map underlying vector objects", "self.OnMenuCmd", "v.rast.stats"),
                ("Indices of point counts in quadrats", "Indices of point counts in quadrats", "self.OnMenuCmd", "v.qcount"),
                )),
              ("","","", "")
              )),
          ("Image", (
              ("Develop images and groups", (
                ("Create/edit imagery group", "Create/edit imagery group", "self.OnMenuCmd", "i.group"),
                ("Target imagery group", "Target imagery group", "self.OnMenuCmd", "i.target"),
                ("","","", ""),
                ("Mosaic up to 4 adjacent images", "Mosaic up to 4 adjacent images", "self.OnMenuCmd", "i.image.mosaic"),
                )),
              ("Manage image colors", (
                ("Balance/enhance color tables for rgb display", "Balance/enhance color tables for rgb display", "self.OnMenuCmd", "i.landsat.rgb"),
                ("Transform HIS to RGB", "Transform HIS to RGB", "self.OnMenuCmd", "i.his.rgb"),
                ("Transform RGB to HIS", "Transform RGB to HIS", "self.OnMenuCmd", "i.rgb.his"),
                )),
              ("Rectify and georeference image group", (
                ("Set ground control points (GCP's) from raster map or keyboard entry", "Set ground control points (GCP's) from raster map or keyboard entry", "self.OnMenuCmd", "i.points"),
                ("Set ground control points (GCP's) from vector map or keyboard entry", "Set ground control points (GCP's) from vector map or keyboard entry", "self.OnMenuCmd", "i.vpoints"),
                ("Affine and Polynomial rectification (rubber sheet)", "Affine and Polynomial rectification (rubber sheet)", "self.OnMenuCmd", "i.rectify"),
                ("Ortho Photo rectification", "Ortho Photo rectification", "self.OnMenuCmd", "i.ortho.photo"),
                )),
              ("","","", ""),
              ("GIPE", (
                ("DN2Rad2Ref", (
                  ("Landsat 7 ETM+", "Landsat 7 ETM+", "self.RunMenuCmd", "i.dn2ref.l7"),
                  ("Landsat 7 ETM+ (from .met)", "Landsat 7 ETM+ (from .met)", "self.RunMenuCmd", "i.dn2full.l7"),
                  ("Terra-Aster", "Terra-Aster", "self.RunMenuCmd", "i.dn2ref.ast"),
                  ("","","", ""),
                  ("Atmospheric correction", "Atmospheric correction", "self.RunMenuCmd", "i.atcorr"),
                  ("Dehaze Landsat", "Dehaze Landsat", "self.RunMenuCmd", "i.landsat.dehaze"),
                  )),
                ("Basic RS processing", (
                  ("Vegetation Index (Tasseled cap)", "Vegetation index (Tasseled cap)", "self.OnMenuCmd", "i.tasscap"),
                  ("Vegetation Indices (13 types)", "Vegetation Indices (13 types)", "self.RunMenuCmd", "i.vi"),
                  ("Vegetation Indices (13 types) cluster", "Vegetation Indices (13 types) cluster", "self.RunMenuCmd", "i.vi.mpi"),
                  ("","","", ""),
                  ("Albedo", "Albedo", "self.RunMenuCmd", "i.albedo"),
                  ("Emissivity (generic from NDVI)", "Emissivity (generic from NDVI)", "self.RunMenuCmd", "i.emissivity"),
                  ("","","", ""),
                  ("Latitude map", "Latitude map", "self.RunMenuCmd", "i.latitude"),
                  ("Sunshine hours (potential)", "Sunshine hours (potential)", "self.RunMenuCmd", "i.sunhours"), 
                  ("Satellite overpass time", "Satellite overpass time", "self.RunMenuCmd", "i.sattime"),
                  )),
                ("","","", ""),
                ("ETo, ETP, ETa", (
                  ("Reference ET (Hargreaves)", "Reference ET (Hargreaves)", "self.RunMenuCmd", "r.evapo.MH"),
                  ("","","", ""),
                  ("Potential ET (Penman-Monteith)", "Potential ET (Penman-Monteith)", "self.OnMenuCmd", "r.evapo.PM"),
                  ("Potential ET (Prestley and Taylor)", "Potential ET (Prestley and Taylor)", "self.RunMenuCmd", "i.evapo.PT"),
                  ("Potential ET (Radiative)", "Potential ET (Radiative)", "self.RunMenuCmd", "i.evapo.potrad"),
                  ("Potential ET (Radiative) from L7DN (.met)", "Potential ET (Radiative) from L7DN (.met)", "self.RunMenuCmd", "i.dn2potrad.l7"),
                  ("","","", ""),
                  ("Actual ET (SEBAL)", "Actual ET (SEBAL)", "self.RunMenuCmd", "i.eb.eta"),
                  ("Actual ET (TSA)", "Actual ET (TSA) NOT WORKING YET", "self.RunMenuCmd", "i.evapo.TSA"),
                  )),
                ("Energy Balance", (
                  ("Surface roughness", "surface roughness", "self.RunMenuCmd", "i.eb.z0m"),
                  ("Delta T", "delta T", "self.RunMenuCmd", "i.eb.deltat"), 
                  ("Net radiation", "net radiation", "self.RunMenuCmd", "i.eb.netrad"),
                  ("","","", ""),
                  ("Displacement height", "Displacement height", "self.RunMenuCmd", "i.eb.disp"),
                  ("Monin-Obukov Length", "Monin-Obukov Length", "self.RunMenuCmd", "i.eb.molength"),
                  ("Psichrometric param. for heat", "psichrometric param. for heat", "self.RunMenuCmd", "i.eb.psi"),
                  ("Blending height wind speed", "blending height wind speed", "self.RunMenuCmd",  "i.eb.ublend"),
                  ("Nominal wind speed", "nominal wind speed", "self.RunMenuCmd", "i.eb.ustar"),
                  ("Aerod. resis. to heat transp.", "aerod. resis. to heat transp.", "self.RunMenuCmd", "i.eb.rah"),
                  ("","","", ""),
                  ("Soil heat flux", "soil heat flux", "self.RunMenuCmd", "i.eb.g0"),
                  ("Sensible heat flux", "sensible heat flux", "self.RunMenuCmd", "i.eb.h0"),
                  ("Sensible heat flux iteration (fixed delta T)", "sensible heat flux iteration (fixed delta T)", "self.RunMenuCmd", "i.eb.h_iter"),
                  ("","","", ""),
                  ("Evaporative fraction", "evaporative fraction", "self.RunMenuCmd", "i.eb.evapfr"),
                  )),
                ("","","", ""),
                ("Biomass", (
                  ("Biomass growth", "Biomass growth", "self.RunMenuCmd", "i.biomass"),
                  )),
                )),
              ("Classify image", (
                ("Classify using pr library", (
                  ("blob", "pr_blob", "self.RunMenuCmd", "i.pr_blob"),
                  ("classify", "pr_classify", "self.RunMenuCmd", "i.pr_classify"),
                  ("features", "pr_features", "self.RunMenuCmd", "i.pr_features"),
                  ("features_additional", "pr_features_additional", "self.RunMenuCmd", "i.pr_features_additional"),
                  ("features_extract", "pr_features_extract", "self.RunMenuCmd", "i.pr_features_extract"),
                  ("features_selection", "pr_features_selection", "self.RunMenuCmd", "i.pr_features_selection"),
                  ("model", "pr_model", "self.RunMenuCmd", "i.pr_model"),
                  ("sites_aggregate", "pr_sites_aggregate", "self.RunMenuCmd", "i.pr_sites_aggregate"),
                  ("statistics", "pr_statistics", "self.RunMenuCmd", "i.pr_statistics"),
                  ("subsets", "pr_subsets", "self.RunMenuCmd", "i.pr_subsets"),
                  ("training", "pr_training", "self.RunMenuCmd", "i.pr_training"),
                  ("uxb", "pr_uxb", "self.RunMenuCmd", "i.pr_uxb"),
                  )),
                ("Clustering input for unsupervised classification", "Clustering input for unsupervised classification", "self.OnMenuCmd", "i.cluster"),
                ("","","", ""),
                ("Maximum likelihood Classification (MLC)", "Maximum likelihood Classification (MLC)", "self.OnMenuCmd", "i.maxlik"),
                ("Sequential maximum a posteriori classification (SMAP)", "Sequential maximum a posteriori classification (SMAP)", "self.OnMenuCmd", "i.smap"),
                ("","","", ""),
                ("Interactive input for supervised classification", "Interactive input for supervised classification", "self.OnMenuCmd", "i.class"),
                ("Non-interactive input for supervised classification (MLC)", "Non-interactive input for supervised classification (MLC)", "self.OnMenuCmd", "i.gensig"),
                ("Non-interactive input for supervised classification (SMAP)", "Non-interactive input for supervised classification (SMAP)", "self.OnMenuCmd", "i.gensigset"),
                ("","","", ""),
                ("Kappa classification accuracy assessment", "Kappa classification accuracy assessment", "self.OnMenuCmd", "r.kappa"),
                )),
              ("Filter image", (
                ("Zero edge crossing detection", "Zero edge crossing detection", "self.OnMenuCmd", "i.zc"),
                ("User defined matrix/convolving filter", "User defined matrix/convolving filter", "self.OnMenuCmd", "r.mfilter"),
                )),
              ("Transform image", (
                ("Canonical component", "Canonical component", "self.OnMenuCmd", "i.cca"),
                ("Principal component", "Principal component", "self.OnMenuCmd", "i.pca"),
                ("Fast Fourier Transform", "Fast Fourier Transform", "self.OnMenuCmd", "i.fft"),
                ("Inverse Fast Fourier Transform", "Inverse Fast Fourier Transform", "self.OnMenuCmd", "i.ifft"),
                ("","","", ""),
                ("Brovey pan sharpening", "Brovey pan sharpening", "self.OnMenuCmd", "i.fusion.brovey"),
                )),
              ("","","", ""),
              ("Quality Analysis", (
                ("Bit pattern comparison for ID of low quality pixels", "Bit pattern comparison for ID of low quality pixels", "self.OnMenuCmd", "r.bitpattern"),
                ("Optimum index factor for LandSat TM", "Optimum index factor for LandSat TM", "self.OnMenuCmd", "i.oif"),
                )),
              ("Report and statistics", (
                ("Report basic file information", "Report basic file information", "self.OnMenuCmd", "r.info"),
                ("Range of image values", "Range of image values", "self.OnMenuCmd", "r.describe"),
                ("","","", ""),
                ("Histogram image", "Histogram image", "self.DispHistogram", ""),
                ("Spectral response", "Spectral response", "self.OnMenuCmd", "i.spectral"),
                )),
              )),
          ("Grid3D", (
            ("Develop grid3D volumes", (
              ("Manage nulls for grid3D volume", "Manage nulls for grid3D volume", "self.RunMenuCmd", "r3.null"),
              ("Manage timestamp for grid3D volume", "Manage timestamp for grid3D volume", "self.RunMenuCmd", "r3.timestamp"),
              )),
              ("Create 3D mask for grid3D operations", "Create 3D mask for grid3D operations", "self.RunMenuCmd", "r3.mask"),
              ("Create 2D raster cross section from grid3d volume", "Create 2D raster cross section from grid3d volume", "self.RunMenuCmd", "r3.cross.rast"),
              ("Map calculator for grid3D operations", "Map calculator for grid3D operations", "self.RunMenuCmd", "r3.mapcalculator"),
              ("Interpolate volume from vector points using splines", "Interpolate volume from vector points using splines", "self.RunMenuCmd", "v.vol.rst"),
              ("","","", ""),
              ("Report and Statistics", (
                ("Display information about grid3D volume", "Display information about grid3D volume", "self.RunMenuCmd", "r3.info"),
                )),
              )),
          ("DB", (
            ("Manage database", (
                ("Connect to database", "Connect to database", "self.RunMenuCmd", "db.connect"),
                ("Login to database", "Login to database", "self.RunMenuCmd", "db.login"),
                ("","","", ""),
                ("Create and add new attribute table to vector map", "Create and add new attribute table to vector map", "self.RunMenuCmd", "v.db.addtable"),
                ("Copy attribute table", "Copy attribute table", "self.RunMenuCmd", "db.copy"),
                ("Remove existing attribute table for vector map", "Remove existing attribute table for vector map", "self.RunMenuCmd", "v.db.droptable"),
                ("","","", ""),
                ("Add columns to table", "Add columns to table", "self.RunMenuCmd", "v.db.addcol"),
                ("Change values in a column", "Change values in a column", "self.RunMenuCmd", "v.db.update"),
                ("Rename a column", "Rename a column", "self.RunMenuCmd", "v.db.renamecol"),
                ("","","", ""),
                ("Test database", "Test database", "self.RunMenuCmd", "db.test"),
                )),
            ("Database information", (
                ("Describe table", "Describe table", "self.RunMenuCmd", "db.describe"),
                ("List columns", "List columns", "self.RunMenuCmd", "db.columns"),
                ("List drivers", "List drivers", "self.RunMenuCmd", "db.drivers"),
                ("List tables", "List tables", "self.RunMenuCmd", "db.tables"),
                )),
              ("","","", ""),
              ("Query", (
                ("Query data in any table", "Query data in any table", "self.RunMenuCmd", "db.select"),
                ("Query vector attribute data", "Query vector attribute data", "self.RunMenuCmd", "db.select"),
                ("Execute SQL statement", "Execute SQL statement", "self.RunMenuCmd", "db.execute"),
                )),
              ("Vector<->database connections", (			
                ("Reconnect vector map to attribute database", "Reconnect vector map to attribute database", "self.RunMenuCmd", "v.db.reconnect.all"),
                ("Set database connection for vector attributes", "Set database connection for vector attributes", "self.RunMenuCmd", "v.db.connect"),
                )),
              )),
          ("Help", (
              ("GRASS help", "GRASS help", "self.RunMenuCmd", "g.manual"),
              ("GIS Manager help", "GIS Manager help", "self.RunMenuCmd", "GIS Manager help"),
              ("","","", ""),
              ("About GRASS", "About GRASS", "self.RunMenuCmd", "About GRASS"),
              ("About System", "About System", "self.RunMenuCmd", "About System"),
              )),
            )]










