MODULE_TOPDIR = ../..

PGM = i.nightlights.intercalibration

ETCFILES = intercalibration_equations intercalibration_coefficients intercalibration_models

include $(MODULE_TOPDIR)/include/Make/Script.make
include $(MODULE_TOPDIR)/include/Make/Python.make

default: script
