MODULE_TOPDIR = ..

SUBDIRS = \
	LandDyn \
	mcda \
	r.area \
	r.basin	\
	r.boxcount \
	r.boxcount.sh \
	r.burn.frict \
	r.clim \
	r.clump2 \
	r.colors.out_sld \
	r.colors.out_vtk \
	r.colors.quantiles \
	r.colors.tools \
	r.convergence \
	r.convert \
	r.csr \
	r.cva \
	r.denoise \
        r.diversity \
	r.flip \
	r.fuzzy \
	r.fuzzy.logic \
	r.fuzzy.system \
	r.game_of_life \
	r.hazard.flood \
	r.in.swisstopo \
	r.inund.fluv \
	r.in.xyz.auto \
	r.ipso \
	r.isoregions \
	r.maxent.lambdas \
	r.out.gmap \
	r.out.gmt \
	r.out.gmt2 \
	r.out.kap_template \
	r.out.kml \
	r.out.maxent_swd \
	r.out.netcdf \
	r.pack \
	r.pi \
	r.prominence \
	r.rast4d \
	r.roughness \
	r.seg \
	r.soils.texture \
	r.stack \
	r.stream.angle \
	r.stream.basins \
	r.stream.del \
	r.stream.distance \
	r.stream.extract \
	r.stream.order \
	r.stream.pos \
	r.stream.stats \
	r.sun.tools \
	r.surf.volcano \
	r.terracost \
	r.terraflow.tools \
	r.threshold \
	r.univar.zonal \
	r.unpack \
	r.viewshed \
	r.vol.dem \
	r.wf \
	r.xtent


include $(MODULE_TOPDIR)/include/Make/Dir.make

default: htmldir

htmldir: subdirs

clean: cleansubdirs
