MODULE_TOPDIR = ../..

PGM = i.spec.unmix

LIBES        = $(GISLIB) $(GMATHLIB) $(IMAGERYLIB) $(RASTERLIB)
DEPENDENCIES = $(GISDEP) $(GMATHDEP) $(IMAGERYDEP) $(RASTERDEP)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd
