MODULE_TOPDIR = ../..

PGM = i.spec.unmix

LIBES     = $(IMAGERYLIB) $(GMATHLIB) $(GISLIB) $(CURSES)
DEPENDENCIES= $(IMAGERYDEP) $(GMATHDEP) $(GISDEP) 

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd
