MODULE_TOPDIR = ..

SUBDIRS = \
	mcda \
	r.boxcount \
	r.boxcount.sh \
	r.burn.frict \
	r.clim \
	r.colors.quantiles \
	r.colors.tools \
	r.convert \
	r.denoise \
	r.game_of_life \
	r.inund.fluv \
	r.in.xyz.auto \
	r.ipso \
	r.isoregions \
	r.out.gmap \
	r.out.gmt \
	r.out.gmt2 \
	r.out.kml \
	r.out.netcdf \
	r.pack \
	r.prominence \
	r.rast4d \
	r.roughness \
	r.soils.texture \
	r.stream.basins \
	r.stream.del \
	r.stream.distance \
	r.stream.extract \
	r.stream.order \
	r.stream.pos \
	r.stream.stats \
	r.sun.tools \
	r.surf.volcano \
	r.terracost \
	r.terraflow.tools \
	r.univar2.zonal \
	r.viewshed \
	r.wf \
	r.xtent

include $(MODULE_TOPDIR)/include/Make/Dir.make

default: htmldir

htmldir: subdirs

clean: cleansubdirs
