MODULE_TOPDIR = ..

SUBDIRS = \
	r.horizon \
	r.sun2

include $(MODULE_TOPDIR)/include/Make/Platform.make
include $(MODULE_TOPDIR)/include/Make/Dir.make

default: htmldir

htmldir: parsubdirs 

clean: cleansubdirs
