MODULE_TOPDIR = ../..

PGM = i.homography

LIBES     = $(IMAGERYLIB) $(GPROJLIB) $(GISLIB) $(VASKLIB) $(CURSES) $(GMATHLIB)
DEPENDENCIES= $(IMAGERYDEP) $(GPROJDEP) $(GISDEP) $(VASKDEP) $(GMATHDEP)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd
