MODULE_TOPDIR = ../..

PGM = r.learn.ml

ETCFILES = raster_learning
		   
include $(MODULE_TOPDIR)/include/Make/Script.make
include $(MODULE_TOPDIR)/include/Make/Python.make

default: script
