MODULE_TOPDIR = ..

SUBDIRS = \
	d.anaglyph \
	d.barb \
	d.edit.rast \
	d.frontline \
	d.hyperlink \
	d.region \
	d.region.box \
	d.zoom.keys

include $(MODULE_TOPDIR)/include/Make/Dir.make

default: htmldir

htmldir: subdirs

clean: cleansubdirs
