MODULE_TOPDIR = ../..

PGM = i.wavelet

LIBES = $(RASTERLIB) $(GISLIB) $(IMAGERYLIB)
DEPENDENCIES = $(RASTERDEP) $(GISDEP) $(IMAGERYDEP)

include $(MODULE_TOPDIR)/include/Make/Module.make


default: cmd
