MODULE_TOPDIR = ../..

PGM = r.dn2potrad.l7

LIBES = $(GPROJLIB) $(GISLIB) $(OPENMP)
DEPENDENCIES = $(GPROJDEP) $(GISDEP)
EXTRA_INC = $(PROJINC)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd
