MODULE_TOPDIR = ../..

PGM = v.in.geoplot

EXTRA_INC = $(PROJINC)
LIBES = $(GISLIB) $(DATETIMELIB) $(VECTLIB)
EXTRA_CFLAGS = -I../../include

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd
