<h2>DESCRIPTION</h2>

<em>r.in.pdal</em> creates a raster map from LAS LiDAR points using the
Point Data Abstraction Library (<a href="https://pdal.io/">PDAL</a>) by
binning the points into a raster map using univariate statistics. The user
may choose from a variety of statistical methods which will be used for
binning when creating the new raster map.
<p>
The computational region of a LiDAR point file can be determined by scanning
the file using the <b>-s</b> flag.
<p>
Optionally <em>r.in.pdal</em> creates an estimated vector footprint area map
of the LAS file when using the <em>footprint</em> parameter (the footprint is
generated by PDAL).
<p>
Since a new raster map is created during the binning, the binning of points
depends on the computational region settings (extent and resolution) which is
by default set to the extent of the LiDAR input file (see more about binning
below). The resulting raster resolution can be specified with the parameter
<em>resolution</em>.
<p>
<em>r.in.pdal</em> is designed for processing massive point cloud datasets,
for example raw LiDAR or sidescan sonar swath data. It has been tested with
large datasets.

<p>
For details concerning raster binning see the manual page of
<em><a href="https://grass.osgeo.org/grass-stable/manuals/r.in.lidar.html">r.in.lidar</a></em>.


<h2>NOTES</h2>

<em>r.in.pdal</em> uses <em><a href="https://grass.osgeo.org/grass-stable/manuals/g.region.html">g.region</a></em> to set
the extent and resolution of the resulting raster and internally
<em><a href="https://grass.osgeo.org/grass-stable/manuals/r.in.xyz.html">r.in.xyz</a></em> to import the LiDAR points.

<h2>EXAMPLES</h2>

<h2>Import LAS file using PDAL</h2>

Import of a LAS file using PDAL into a mapset in the sample NC SPM
location. The sample LAS file is available
<a href="https://www.grassbook.org/wp-content/uploads/ncexternal/lidar_raleigh_nc_spm_height_feet.las">here</a>.

<div class="code"><pre>
# check metadata
pdal info --summary lidar_raleigh_nc_spm_height_feet.las

# scan extent and exit
r.in.pdal input=lidar_raleigh_nc_spm_height_feet.las output=lidar_raleigh -s

# scan extent (g.region style) and exit
r.in.pdal input=lidar_raleigh_nc_spm_height_feet.las output=lidar_raleigh -s -g
# n=228500 s=215000.01 w=633370.82 e=645000 t=558.87 b=88.5

# set computation region to this extent
g.region n=228500 s=215000.01 w=633370.82 e=645000 -p

# import while aligning pixel geometry to existing "elevation" 10m res. raster map
# specifying EPSG manually because SRS information is missing in this LAS file
r.in.pdal input=lidar_raleigh_nc_spm_height_feet.las raster_reference=elevation \
          resolution=10 output=lidar_raleigh method=mean

# optionally: footprint=lidar_raleigh_footprint

# visualize
d.mon wx0
g.list vector
d.rast lidar_raleigh
d.vect streets_wake

# analyse differences between DEM and rasterized point cloud
# LAS files come with height in US feet units
r.mapcalc "diff = elevation - lidar_raleigh * 0.3048006096012192"
r.univar -e diff
</pre></div>

<div align="center" style="margin: 10px">
<a href="r_in_pdal.png">
<img src="r_in_pdal.png" width="600" height="697" alt="Figure: View showing the difference of the elevation and the LiDAR point data binned to raster map with r.in.pdal" border="0">
</a><br>
<i>Figure: View showing the difference of the elevation map and LiDAR point data binned to raster map with r.in.pdal</i>
</div>

<div align="center" style="margin: 10px">
<a href="r_in_pdal_footprint.jpg">
<img src="r_in_pdal_footprint.jpg" width="600" height="497" alt="Figure: LiDAR cloud footprint" border="0">
</a><br>
<i>Figure: LiDAR cloud footprint</i>
</div>

<h2>Import LAZ file using PDAL docker</h2>
Import of a LAZ file using PDAL docker into a mapset in the sample NC SPM
location. The sample LAZ file is available
<a href="https://github.com/PDAL/PDAL/raw/master/test/data/laz/simple.laz">here</a>.

<div class="code"><pre>
# pulling official PDAL docker image
docker pull pdal/pdal

# using PDAL docker as command with mounted data volume
# (caution: the LAZ file has to be stored in the mounted folder! (here: $(pwd)))
export pdal_docker="docker run --rm -v $(pwd):/data -t pdal/pdal pdal"

# scan extent and exit
r.in.pdal input=/data/simple.laz output=lidar -s pdal_cmd="$pdal_docker"

# scan extent (g.region style) and exit
r.in.pdal input=/data/simple.laz output=lidar -s -g pdal_cmd="$pdal_docker"
# n=853535.43 s=848899.7 w=635619.85 e=638982.55 t=586.38 b=406.59

# set computation region to this extent
g.region n=853535.43 s=848899.7 w=635619.85 e=638982.55 -p

# import data
r.in.pdal input=/data/simple.laz output=lidar_perc95 method=percentile pth=95 pdal_cmd="$pdal_docker"

r.univar lidar_perc95
</pre></div>


<h2>SEE ALSO</h2>

<em>
<a href="https://grass.osgeo.org/grass-stable/manuals/r.in.xyz.html">r.in.xyz</a>,
<a href="https://grass.osgeo.org/grass-stable/manuals/r.in.lidar.html">r.in.lidar</a>,
<a href="https://grass.osgeo.org/grass-stable/manuals/v.in.lidar.html">v.in.lidar</a>
</em>


<h2>AUTHORS</h2>

Anika Bettge, mundialis GmbH &amp; Co. KG<br>
Vaclav Petras,
<a href="https://geospatial.ncsu.edu/geoforall/">NCSU GeoForAll Lab</a>
(projection, computational region)
<p>
Documentation: Markus Neteler, mundialis GmbH &amp; Co. KG
