MODULE_TOPDIR = ../..

PGM = r3.profile

LIBES = $(RASTER3DLIB) $(RASTERLIB) $(GISLIB) $(MATHLIB)
DEPENDENCIES = $(RASTER3DDEP) $(RASTERDEP) $(GISDEP)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd
