MODULE_TOPDIR = ../..

PGM = i.homography

EXTRA_INC = $(PROJINC)

LIBES     = $(IMAGERYLIB) $(GPROJLIB) $(GISLIB) $(GMATHLIB)
DEPENDENCIES= $(IMAGERYDEP) $(GPROJDEP) $(GISDEP) $(GMATHDEP)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd
