MODULE_TOPDIR = ../..

PGM = r.segment

LIBES = $(GISLIB) $(RASTERLIB) $(SEGMENTLIB)
DEPENDENCIES = $(GISDEP) $(RASTERDEP) $(SEGMENTDEP)


include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd

