MODULE_TOPDIR = ..

SUBDIRS = \
	r.pi.corrwin \
	r.pi.export \
	r.pi.import \
	r.pi.index \
	r.pi.rectangle

include $(MODULE_TOPDIR)/include/Make/Dir.make

default: htmldir

htmldir: subdirs

clean: cleansubdirs
