MODULE_TOPDIR = ../..

PGM = v.class.ml

ETCFILES = training_extraction ml_classifiers ml_functions sqlite2npy npy2table

include $(MODULE_TOPDIR)/include/Make/Script.make
include $(MODULE_TOPDIR)/include/Make/Python.make

default: script
