MODULE_TOPDIR = ../..

PGM = r.resamp.tps

LIBES = $(RASTERLIB) $(BTREE2LIB) $(SEGMENTLIB) $(GISLIB) $(MATHLIB)
DEPENDENCIES = $(RASTERDEP) $(BTREE2DEP) $(SEGMENTDEP) $(GISDEP)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd

