MODULE_TOPDIR = ../..

PGM=r.green

SUBDIRS = r.green.hydro/libhydro \
	r.green.biomassfor \
	r.green.hydro \
	libgreen

include $(MODULE_TOPDIR)/include/Make/Dir.make

default: parsubdirs htmldir

install: installsubdirs
