
MODULE_TOPDIR = ../..

PGM = v.path.obstacles

LIBES        = $(VECTLIB) $(GISLIB)
DEPENDENCIES = $(VECTDEP) $(GISDEP)
EXTRA_INC = $(VECT_INC)
EXTRA_CFLAGS = $(VECT_CFLAGS) -Wall

include $(MODULE_TOPDIR)/include/Make/Module.make


default: cmd




