MODULE_TOPDIR = ../../..

PGM = r.watershed.ram.fast

LIBES = $(GISLIB)
DEPENDENCIES = $(GISDEP)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: etc 

htmletc:
	@echo "No docs to generate." 
