MODULE_TOPDIR = ../../..

PGM = r.watershed2.ram

LIBES = $(GISLIB)
DEPENDENCIES = $(GISDEP)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: etc 

htmletc:
	@echo "No docs to generate." 
