
MODULE_TOPDIR = ..

SUBDIRS = \
	v.adehabitat.clusthr \
	v.adehabitat.kernelUD \
	v.adehabitat.mcp

include $(MODULE_TOPDIR)/include/Make/Platform.make
include $(MODULE_TOPDIR)/include/Make/Dir.make

default: htmldir

htmldir: parsubdirs

clean: cleansubdirs
