MODULE_TOPDIR = ../../../trunk

PGM = r.accumulate

LIBES = $(GISLIB) $(RASTERLIB) $(VECTORLIB)
DEPENDENCIES = $(GISDEP) $(RASTERDEP) $(VECTORDEP)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd
