MODULE_TOPDIR = ../../..

PGM = i.modis.download

include $(MODULE_TOPDIR)/include/Make/Script.make

default: script

# $(ETC)/i.modis/i.modis.download/%: % | $(ETC)/i.modis/i.modis.download
# 	$(INSTALL) $< $@
#
# $(ETC)/i.modis/i.modis.download:
# 	$(MKDIR) $@
