MODULE_TOPDIR = ../../..

PGM = t.stac.collection

include $(MODULE_TOPDIR)/include/Make/Script.make

default: script

# $(ETC)/t.stac/t.stac.collection/%: % | $(ETC)/t.stac/t.stac.collection
# 	$(INSTALL) $< $@
#
# $(ETC)/t.stac/t.stac.collection:
# 	$(MKDIR) $@
