MODULE_TOPDIR = ../..

PGM = i.hyper.import

EXTRA_HTML_FILES = i_hyper_import_prisma_swir_geology.png

include $(MODULE_TOPDIR)/include/Make/Script.make
include $(MODULE_TOPDIR)/include/Make/Html.make

default: script html
