MODULE_TOPDIR = ..

SUBDIRS = \
	v.colors2 \
	v.in.ply \
	v.in.redwg \
	v.in.wfs2 \
	v.median \
	v.out.ply \
	v.pack \
	v.surf.icw \
	v.unpack

include $(MODULE_TOPDIR)/include/Make/Dir.make

default: subdirs
