MODULE_TOPDIR = ..

# v.mapcalc

SUBDIRS = \
	v.area.stats \
	v.area.weigh \
	v.build.pg \
	v.centerline \
	v.centerpoint \
	v.civil \
	v.class.ml \
	v.class.mlpy \
	v.colors2 \
	v.concave.hull \
	v.convert \
	v.convert.all \
	v.delaunay3d \
	v.ellipse \
	v.external.all \
	v.flexure \
	v.habitat.dem \
	v.in.geopaparazzi \
	v.in.gps \
	v.in.ply \
	v.in.redwg \
	v.in.wfs2 \
	v.lfp \
	v.lidar.mcc \
	v.link.precip \
	v.median \
	v.neighborhoodmatrix \
	v.net.salesman.opt \
	v.out.gps \
	v.out.ply \
	v.out.png \
	v.ply.rectify \
	v.stats \
	v.surf.icw \
	v.surf.mass \
	v.transects \
	v.what.strds

include $(MODULE_TOPDIR)/include/Make/Dir.make

default: subdirs
