MODULE_TOPDIR = ..

SUBDIRS = \
	adehabitat \
	v.autokrige \
	v.curvature \
	v.db.calc \
	v.eqsm \
	v.in.adcirc_grid \
	v.in.gama \
	v.in.geoplot \
	v.in.gshhs \
	v.in.mbsys_fnv \
	v.in.ncdc \
	v.in.postgis \
	v.ldm \
	v.mainchannel \
	v.out.ascii.db \
	v.out.ascii.mat \
	v.out.gmt \
	v.out.postgis \
	v.points.cog \
	v.profile \
	v.random.cover \
	v.rast.stats2 \
	v.selmany \
	v.strahler \
	v.surf.icw \
	v.swathwidth \
	v.transect.kia \
	v.transects \
	v.what.rast.buffer

include $(MODULE_TOPDIR)/include/Make/Dir.make

default: htmldir

htmldir: subdirs

clean: cleansubdirs
