MODULE_TOPDIR =../..

PGM = r.agent.aco


SUBDIRS = libagent

include $(MODULE_TOPDIR)/include/Make/Dir.make
include $(MODULE_TOPDIR)/include/Make/Script.make

default: script parsubdirs

install: installsubdirs
