MODULE_TOPDIR = ..

SUBDIRS = \
	d.edit.rast \
	d.frame.split \
	d.region \
	d.region.box \
	d.shortcuts

include $(MODULE_TOPDIR)/include/Make/Dir.make

default: htmldir

htmldir: subdirs

clean: cleansubdirs
