MODULE_TOPDIR =../..

PGM = r.futures

SUBDIRS = \
		r.futures.calib \
		r.futures.devpressure \
		r.futures.pga

include $(MODULE_TOPDIR)/include/Make/Dir.make

default: parsubdirs htmldir

install: installsubdirs
