MODULE_TOPDIR = ../..

PGM = r.sun.angle

LIBES = $(GPROJLIB) $(RASTERLIB) $(GISLIB)
DEPENDENCIES = $(GPROJDEP) $(RASTERDEP) $(GISDEP)

EXTRA_INC = $(PROJINC)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd
