#include "defs.h"

#ifndef GLOBAL
#define GLOBAL extern
#define INIT(x)
#else
#define INIT(x) = x
#endif

GLOBAL int G_get_color();

GLOBAL int SCREEN_TOP;
GLOBAL int SCREEN_BOTTOM;
GLOBAL int SCREEN_LEFT;
GLOBAL int SCREEN_RIGHT;

GLOBAL View *VIEW_MAP1;
GLOBAL View *VIEW_TITLE1;
GLOBAL View *VIEW_MAP1_ZOOM;
GLOBAL View *VIEW_TITLE1_ZOOM;
GLOBAL View *VIEW_IMAGE;
GLOBAL View *VIEW_TITLE_IMAGE;
GLOBAL View *VIEW_INFO;
GLOBAL View *VIEW_EXIT;
GLOBAL View *VIEW_EMPTY;
GLOBAL View *VIEW_MENU;

GLOBAL int dotsize INIT(4);

GLOBAL int THE_COLORS[10];

#define BLACK  THE_COLORS[0]
#define BLUE   THE_COLORS[1]
#define BROWN  THE_COLORS[2]
#define GREEN  THE_COLORS[3]
#define GREY   THE_COLORS[4]
#define ORANGE THE_COLORS[5]
#define PURPLE THE_COLORS[6]
#define RED    THE_COLORS[7]
#define WHITE  THE_COLORS[8]
#define YELLOW THE_COLORS[9]

#undef INIT
