#pragma once

#include "defs.h"
#include "global.h"

#ifndef GLOBAL
#define GLOBAL extern
#define INIT(x)
#else
#define INIT(x) = x
#endif

GLOBAL int SCREEN_TOP;
GLOBAL int SCREEN_BOTTOM;
GLOBAL int SCREEN_LEFT;
GLOBAL int SCREEN_RIGHT;

GLOBAL View *VIEW_MAP1;
GLOBAL View *VIEW_TITLE1;
GLOBAL View *VIEW_MAP1_ZOOM;
GLOBAL View *VIEW_TITLE1_ZOOM;
GLOBAL View *VIEW_IMAGE;
GLOBAL View *VIEW_TITLE_IMAGE;
GLOBAL View *VIEW_INFO;
GLOBAL View *VIEW_EXIT;
GLOBAL View *VIEW_EMPTY;
GLOBAL View *VIEW_MENU;

GLOBAL int dotsize INIT(4);

GLOBAL int THE_COLORS[10];

#define IPR_BLACK  THE_COLORS[0]
#define IPR_BLUE   THE_COLORS[1]
#define IPR_BROWN  THE_COLORS[2]
#define IPR_GREEN  THE_COLORS[3]
#define IPR_GREY   THE_COLORS[4]
#define IPR_ORANGE THE_COLORS[5]
#define IPR_PURPLE THE_COLORS[6]
#define IPR_RED    THE_COLORS[7]
#define IPR_WHITE  THE_COLORS[8]
#define IPR_YELLOW THE_COLORS[9]

#undef INIT
