
MODULE_TOPDIR = ..

# display gui misc raster3d
SUBDIRS = \
	db \
	display \
	general \
	imagery \
	raster \
	vector \
	temporal

include $(MODULE_TOPDIR)/include/Make/Dir.make

default: parsubdirs

