#!/bin/sh
# svngrep -- by Hamish Bowman, 30 Apr 2008
#    released to the Public Domain
#
# simple wrapper script for grep which will skip false positives in
#  /.svn/, .tmp.html, and binary files
#
# e.g.  trunk$ svngrep -r scalebar *

# TODO:
# + enumerate $* to "$1" "$2" "$3" ...  so grouped 'search items' are not split.
#       loop '$#' with shell-proof \" quotes?
# + ignore "dist.`uname m`"  and  "^ChangeLog:" entries

grep -I $* | grep -v '/\.svn/\|\.tmp\.html:\|locale/po/\|^dist\.'
