<h2>DESCRIPTION</h2>

<em>v.stream.network</em> populates the attribute table of a river network built by <a href="https://grass.osgeo.org/grass-stable/manuals/r.stream.extract.html">r.stream.extract</a> with five new columns that define the nodes and links within a river network. These are (default names given):
<ul>
  <li><em>x1</em>, <em>y1</em>: upstream coordinates</li>
  <li><em>x2</em>, <em>y2</em>: downstream coordinates</li>
  <li><em>tostream</em>: category number of the next stream; is equal to 0 if the stream flows off of the map</li>
</ul>

Any stream-like network will work, but the lines need to be connected.
In terms of graph theory, a tree and forest are supported. Behavior for
a cyclic graph is undefined.

<h2>NOTES</h2>

<b>streams</b> is a set of vector lines that is generated by r.stream.extract. It is recommended to be built as follows (Python code):

<div class="code"><pre>
# Choose elevation map and threshold
elevation = srtm
threshold = 1E6 # [m**2], minimum catchment size = 1 km**2
# Build a map of cell areas: pick one of these
# km2 is more intuitive, but 1 km2 is the threshold for the smallest
# threshold catchment size
r.mapcalc('cellArea_meters2 = '+str(reg.nsres)+' * '+str(reg.ewres), overwrite=True)
r.mapcalc("cellArea_km2 = cellArea_meters2 / 10^6", overwrite=True)

# Use r.watershed to build a drainage basin with units of length**2
# instead of arbitrary units (cells)
r.watershed(elevation=elevation, flow='cellArea_meters2', accumulation='drainageArea_m2', drainage='drainageDirection', stream='streams', threshold=thresh, flags='s', overwrite=True)
# Note that this will include areas of negative (i.e. offmap) flow accumulation

# Build watershed network using r.stream.extract: single-flow-direction (SFD)
print "Building drainage network"
r.stream_extract(elevation=elevation, accumulation='drainageArea_m2', threshold=thresh, d8cut=0, mexp=0, stream_raster='streams', stream_vector='streams', direction='draindir', overwrite=True)
</pre></div>

<h2>REFERENCES</h2>

<ul>
  <li>
    Ng, G-H. Crystal, Andrew D. Wickert, Lauren D. Somers, Leila Saberi,
    Collin Cronkite-Ratcliff, Richard G. Niswonger,
    and Jeffrey M. McKenzie.
    "GSFLOW–GRASS v1. 0.0: GIS-enabled hydrologic modeling of coupled
    groundwater–surface-water systems."
    <em>Geoscientific Model Development</em> 11 (2018): 4755-4777.
    <a href="https://doi.org/10.5194/gmd-11-4755-2018">DOI 10.5194/gmd-11-4755-2018</a>
  </li>
</ul>

<h2>SEE ALSO</h2>

<em>
<a href="https://grass.osgeo.org/grass-stable/manuals/r.stream.extract.html">r.stream.extract</a>,
<a href="v.stream.order.html">v.stream.order</a>
</em>

<h2>AUTHOR</h2>

Andrew D. Wickert
