MODULE_TOPDIR = ..

SUBDIRS = \
        m.dst.create \
	m.dst.source \
	m.dst.update \
	m.dst.view \
	m.filter.gen

include $(MODULE_TOPDIR)/include/Make/Dir.make

default: htmldir

htmldir: subdirs

clean: cleansubdirs
