MODULE_TOPDIR = ../../..

PGM = i.modis.download

include $(MODULE_TOPDIR)/include/Make/Script.make

default: script

# $(ETC)/r.modis/r.modis.download/%: % | $(ETC)/r.modis/r.modis.download
# 	$(INSTALL) $< $@
# 
# $(ETC)/r.modis/r.modis.download:
# 	$(MKDIR) $@
