#!/bin/sh
# functions to remove raster map entries to the grass sql database 

source globals/defines.sh

remove_raster_map () 
{
MAPNAME=$1
GROUP_TABLE="${RASTER_GROUP_TABLE_PREFIX}_${MAPNAME}"
REFERENCE_TABLE="${RASTER_REFERENCE_TABLE_PREFIX}_${MAPNAME}"
METADATA_TABLE="${RASTER_METADATA_TABLE_PREFIX}_${MAPNAME}"
CATEGORY_TABLE="${RASTER_CATEGORY_TABLE_PREFIX}_${MAPNAME}"
TEMPORAL_TABLE="${RASTER_TEMPORAL_TABLE_PREFIX}_${MAPNAME}"

#$DBM $DATABASE "DROP TABLE $REFERENCE_TABLE"
#$DBM $DATABASE "DROP TABLE $METADATA_TABLE"
#$DBM $DATABASE "DROP TABLE $GROUP_TABLE"
#$DBM $DATABASE "DROP TABLE $CATEGORY_TABLE"
#$DBM $DATABASE "DROP TABLE $TEMPORAL_TABLE"

echo "REMOVE $MAPNAME FROM $RASTER_TABLE_NAME"
$DBM $DATABASE "DELETE FROM $RASTER_TABLE_NAME  WHERE name='$MAPNAME'"

}

remove_raster_map_metadata ()
{
MAPNAME=$1
echo "REMOVE $MAPNAME FROM $RASTER_METADATA_TABLE_NAME"
$DBM $DATABASE "DELETE FROM $RASTER_METADATA_TABLE_NAME  WHERE name='$MAPNAME'"
}

remove_raster_map_time () 
{
MAPNAME=$1
echo "REMOVE $MAPNAME FROM $RASTER_TIME_TABLE_NAME"
$DBM $DATABASE "DELETE FROM $RASTER_TIME_TABLE_NAME  WHERE name='$MAPNAME'"
}
