Index: Makefile
===================================================================
--- Makefile	(revision 47502)
+++ Makefile	(working copy)
@@ -9,10 +9,10 @@
 
 ETCDIR = $(ETC)/gui/wxpython
 
-SRCFILES := $(wildcard scripts/* compat/* gui_modules/* icons/*.* xml/*) gis_set.py gis_set_error.py wxgui.py README
+SRCFILES := $(wildcard scripts/* compat/* gui_modules/* gui_modules/wms/* icons/*.* xml/*) gis_set.py gis_set_error.py wxgui.py README
 DSTFILES := $(patsubst %,$(ETCDIR)/%,$(SRCFILES)) $(patsubst %.py,$(ETCDIR)/%.pyc,$(filter %.py,$(SRCFILES)))
 
-DSTDIRS := $(patsubst %,$(ETCDIR)/%,compat gui_modules icons scripts xml)
+DSTDIRS := $(patsubst %,$(ETCDIR)/%,compat gui_modules gui_modules/wms icons scripts xml)
 
 default: $(DSTFILES) menustrings.py
 	$(MAKE) parsubdirs
