#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Sat Jul 30 22:23:14 2011

import wx

# begin wxGlade: extracode
# end wxGlade



class PopUpFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: PopUpFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.passworddescription = wx.StaticText(self, -1, "   Enter password")
        self.text_ctrl_1 = wx.TextCtrl(self, -1, "", style=wx.TE_PASSWORD)
        self.passwordEnter = wx.Button(self, -1, "Enter")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: PopUpFrame.__set_properties
        self.SetTitle("EnterPassword")
        self.text_ctrl_1.SetMinSize((200, 25))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: PopUpFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add(self.passworddescription, 0, 0, 0)
        sizer_1.Add(self.text_ctrl_1, 0, 0, 0)
        sizer_1.Add(self.passwordEnter, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

# end of class PopUpFrame


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = PopUpFrame(None, -1, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()

def PasswordPopUpFrame():
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = PopUpFrame(None, -1, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()