#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Sat Aug  6 14:09:41 2011

import wx
from wx.lib.pubsub import Publisher
# begin wxGlade: extracode
# end wxGlade



class SaveFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: SaveFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.unsaved_label = wx.StaticText(self, -1, "                    You have unsaved changes \n                               Do you want to\n")
        self.SaveButton = wx.Button(self, -1, "Save")
        self.DontSaveButton = wx.Button(self, -1, "Don't Save")
        self.button_3 = wx.Button(self, -1, "Cancel")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.OnSave, self.SaveButton)
        self.Bind(wx.EVT_BUTTON, self.OnDontSave, self.DontSaveButton)
        self.Bind(wx.EVT_BUTTON, self.OnCancel, self.button_3)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: SaveFrame.__set_properties
        self.SetTitle("frame_1")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: SaveFrame.__do_layout
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2.Add(self.unsaved_label, 0, 0, 0)
        sizer_3.Add(self.SaveButton, 0, 0, 0)
        sizer_3.Add(self.DontSaveButton, 0, 0, 0)
        sizer_3.Add(self.button_3, 0, 0, 0)
        sizer_2.Add(sizer_3, 0, wx.EXPAND, 0)
        self.SetSizer(sizer_2)
        sizer_2.Fit(self)
        self.Layout()
        # end wxGlade

    def OnSave(self, event): # wxGlade: SaveFrame.<event_handler>
        print "Event handler `OnSave' not implemented!"
        msg = ''
        Publisher().sendMessage(("PopupSaveRequest"), msg)
        event.Skip()
        self.Destroy()

    def OnDontSave(self, event): # wxGlade: SaveFrame.<event_handler>
        print "Event handler `OnDontSave' not implemented!"
        msg = ''
        Publisher().sendMessage(("PopupNotSaveRequest"), msg)
        event.Skip()
        self.Destroy()

    def OnCancel(self, event): # wxGlade: SaveFrame.<event_handler>
        print "Event handler `OnCancel' not implemented!"
        msg = ''
        Publisher().sendMessage(("PopupCancelRequest"), msg)
        event.Skip()
        self.Destroy()

# end of class SaveFrame

def SavePopUp():
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    dialog_1 = SaveFrame(None, -1, "")
    app.SetTopWindow(dialog_1)
    dialog_1.Show()
    app.MainLoop()

if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    dialog_1 = SaveFrame(None, -1, "")
    app.SetTopWindow(dialog_1)
    dialog_1.Show()
    app.MainLoop()