MODULE_TOPDIR = ../..

SUBDIRS = \
        v.civil.river \
        v.civil.road \
        v.civil.tools \
        v.civil.topo

include $(MODULE_TOPDIR)/include/Make/Dir.make

default: parsubdirs

install: installsubdirs
