MODULE_TOPDIR = ../..

include $(MODULE_TOPDIR)/include/Make/Dir.make

SUBDIRS = \
        PRLIB \
	i.pr_blob \
	i.pr_classify \
	i.pr_features \
	i.pr_features_additional \
	i.pr_features_extract \
	i.pr_features_selection \
	i.pr_model \
	i.pr_statistics \
	i.pr_subsets \
	i.pr_training \
	i.pr_uxb \
	i.pr_sites_aggregate

default: subdirs

clean: cleansubdirs

install: installsubdirs
