/* Auto-generated by tools/extract_tables.py from 6SV2.1 Fortran source */
#pragma once

/* Aerosol component optical properties at 20 reference wavelengths (wldis).
 * Components: 0=dust, 1=wate(water-soluble), 2=ocea(oceanic), 3=soot
 * For standard aerosol models (continental/maritime/urban/desert):
 *   each model is a mixture of these 4 components.
 */

#define AEROSOL_NCOMP 4
#define AEROSOL_NWL   20
#define AEROSOL_NQUAD 83

extern const float aerosol_dust_ext[20];
extern const float aerosol_dust_sca[20];
extern const float aerosol_dust_asy[20];
extern const float aerosol_dust_pha[20][83];

extern const float aerosol_wate_ext[20];
extern const float aerosol_wate_sca[20];
extern const float aerosol_wate_asy[20];
extern const float aerosol_wate_pha[20][83];

extern const float aerosol_ocea_ext[20];
extern const float aerosol_ocea_sca[20];
extern const float aerosol_ocea_asy[20];
extern const float aerosol_ocea_pha[20][83];

extern const float aerosol_soot_ext[20];
extern const float aerosol_soot_sca[20];
extern const float aerosol_soot_asy[20];
extern const float aerosol_soot_pha[20][83];

/* Standard aerosol model mixing ratios [dust, wate, ocea, soot] */
/* Models: 0=continental, 1=maritime, 2=urban */
extern const float aerosol_std_mix[3][4];
