MODULE_TOPDIR = ../../..

PRINCLUDE = ../include/
EXTRA_CFLAGS = -I$(PRINCLUDE)
EXTRA_LIBS = $(GMATHLIB) $(GISLIB) $(MATHLIB)

LIB_NAME = grass_pr.$(GRASS_LIB_VERSION_NUMBER)

include $(MODULE_TOPDIR)/include/Make/Lib.make

default: lib

