MODULE_TOPDIR = ..

SUBDIRS = \
	r.area/ \
	r.clump2/ \
	r.convergence/ \
	r.convert/ \
	r.fuzzy/ \
	r.in.modis/ \
	r.stream/ \
	r.stream.extract

include $(MODULE_TOPDIR)/include/Make/Dir.make

default: subdirs

