MODULE_TOPDIR = ..

SUBDIRS = \
	r.agent \
	r.area \
	r.basin \
	r.bioclim \
	r.convergence \
	r.convert \
	r.crater \
	r.damflood \
	r.diversity \
	r.droka \
	r.edm.eval \
	r.fidimo \
	r.findtheriver \
	r.flip \
	r.forestfrag \
	r.fuzzy.set \
	r.fuzzy.logic \
	r.fuzzy.system \
	r.gdd \
	r.geomorphon \
	r.gwr \
	r.hants \
	r.hazard.flood \
	r.houghtransform \
	r.hydrodem \
	r.hypso \
	r.in.arc \
	r.in.srtm.region \
	r.in.wcs \
	r.lake.series \
	r.lfp \
	r.local.relief \
	r.los \
	r.massmov \
	r.mcda.ahp \
	r.mcda.input \
	r.mcda.output \
	r.mcda.roughset \
	r.mess \
	r.modis \
	r.mwprecip \
	r.northerness.easterness \
	r.out.arc \
	r.out.tiff \
	r.popgrowth \
	r.random.weight \
	r.regression.series \
	r.roughness.vector \
	r.segment \
	r.shaded.pca \
	r.shalstab \
	r.skyview \
	r.soillossbare \
	r.stream.basins \
	r.stream.channel \
	r.stream.distance \
	r.stream.order \
	r.stream.segment \
	r.stream.slope \
	r.stream.snap \
	r.stream.stats \
	r.sun.daily \
	r.sun.hourly \
	r.surf.nnbathy \
	r.threshold \
	r.to.vect.lines \
	r.to.vect.tiled \
	r.traveltime \
	r.univar2 \
	r.valley.bottom \
	r.vif \
	r.vol.dem \
	r.width.funct
	

include $(MODULE_TOPDIR)/include/Make/Dir.make

default: subdirs

