MODULE_TOPDIR = ../..

PGM = i.spec.sam

EXTRALIB=meschach.a
LIBES     = $(IMAGERYLIB) $(GMATHLIB) $(GISLIB)
DEPENDENCIES= $(IMAGERYDEP) $(GMATHDEP) $(GISDEP)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd
