MODULE_TOPDIR = ../../..

PGM = r.le.trace

LIBES = $(DISPLAYLIB) $(GISLIB) $(RASTERLIB)
DEPENDENCIES = $(DISPLAYDEP) $(GISDEP) $(RASTERDEP)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd
