#!/bin/sh
# script to make backporting easier: this one _pulls from_ trunk.
#
#  by Hamish Bowman, Feb 2011; released to the public domain
#
# pulls a recent change from relbr70 into another branch by rev number
# you should be in the top source dir of the branch you are pulling
# into. mind that you might want to run 'svn propdel svn:mergeinfo .'
# before doing an untargeted 'svn commit'.

if [ $# -eq 1 ] ; then
  svn merge -c $1 https://svn.osgeo.org/grass/grass/branches/releasebranch_7_0
else
  echo "usage: cd grass65; svn70merge rev_number"
fi
