MODULE_TOPDIR = ../..

PGM = r.futures.simulation

LIBES = $(SEGMENTLIB) $(RASTERLIB) $(GISLIB) $(MATHLIB) $(DATETIMELIB)
DEPENDENCIES = $(SEGMENTDEP) $(RASTERDEP) $(GISDEP) $(DATETIMEDEP)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd
