#!/usr/bin/env python3
"""Regenerate gas k-distribution arrays from the original 6SV2.1 sources."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


NUMBER = re.compile(r"[-+]?\d*\.?\d+(?:[DEde][-+]?\d+)?")
GASES = {
    "wava": range(1, 7),
    "dica": range(1, 4),
    "oxyg": range(3, 7),
    "ozon": range(1, 2),
    "niox": range(1, 7),
    "meth": range(1, 7),
    "moca": range(1, 7),
}


def parse_acr(path: Path) -> list[float]:
    """Read all 256 x 8 ACR values from one fixed-form Fortran source."""
    values: list[float] = []
    in_data = False
    for line in path.read_text(encoding="ascii").splitlines():
        if "DATA ((ACR(" in line.upper():
            in_data = True
            continue
        if not in_data or len(line) < 7 or line[5].isspace():
            continue
        for value in NUMBER.findall(line[6:]):
            values.append(float(value.replace("D", "E").replace("d", "e")))
    expected = 256 * 8
    if len(values) != expected:
        raise ValueError(f"{path}: expected {expected} ACR values, found {len(values)}")
    return values


def format_table(name: str, bands: list[list[float]]) -> str:
    lines = [f"const float gas_acr_{name}[6][256][8] = {{"]
    for band_index, values in enumerate(bands, start=1):
        lines.append(f"    /* band {band_index} */")
        lines.append("    {")
        for index in range(256):
            row = values[index * 8 : (index + 1) * 8]
            formatted = ", ".join(f"{value:.7E}f" for value in row)
            suffix = "," if index < 255 else ""
            lines.append(f"        {{{formatted}}}{suffix}")
        suffix = "," if band_index < 6 else ""
        lines.append(f"    }}{suffix}")
    lines.append("};")
    return "\n".join(lines)


def parse_data_array(path: Path, name: str, expected: int) -> list[float]:
    values: list[float] = []
    in_data = False
    for line in path.read_text(encoding="ascii").splitlines():
        if re.search(rf"DATA\s*\(\s*{name}\s*\(", line, re.IGNORECASE):
            in_data = True
            continue
        if not in_data:
            continue
        if len(line) >= 7 and not line[5].isspace():
            values.extend(
                float(value.replace("D", "E").replace("d", "e"))
                for value in NUMBER.findall(line[6:])
            )
        if "/" in line:
            break
    if len(values) != expected:
        raise ValueError(
            f"{path}: expected {expected} {name} values, found {len(values)}"
        )
    return values


def format_vector(name: str, values: list[float]) -> str:
    lines = [f"const float {name}[{len(values)}] = {{"]
    for index in range(0, len(values), 6):
        row = ", ".join(f"{value:.7E}f" for value in values[index : index + 6])
        suffix = "," if index + 6 < len(values) else ""
        lines.append(f"    {row}{suffix}")
    lines.append("};")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=Path, help="6SV2.1 source directory")
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(__file__).resolve().parents[1] / "src" / "gas_tables.c",
    )
    args = parser.parse_args()

    tables = []
    for name, populated_bands in GASES.items():
        bands: list[list[float]] = []
        for band in range(1, 7):
            if band in populated_bands:
                bands.append(parse_acr(args.source / f"{name.upper()}{band}.f"))
            else:
                bands.append([0.0] * (256 * 8))
        tables.append(format_table(name, bands))

    abstra = args.source / "ABSTRA.f"
    tables.append(format_vector("gas_co3_ozon", parse_data_array(abstra, "co3", 102)))
    tables.append(format_vector("gas_cch2o", parse_data_array(abstra, "cch2o", 15)))

    header = (
        "/* Auto-generated by tools/extract_gas_tables.py from 6SV2.1 "
        'Fortran source */\n#include "gas_tables.h"\n\n'
    )
    args.output.write_text(
        header + "\n\n".join(tables) + "\n",
        encoding="ascii",
    )


if __name__ == "__main__":
    main()
