#!/usr/bin/env python3
"""Extract aerosol polarization and BDM tables from 6SV2.1 Fortran."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


NUMBER = re.compile(r"[-+]?\d*\.?\d+(?:[DEde][-+]?\d+)?")
COMPONENTS = ("dust", "wate", "ocea", "soot")


def numbers(text: str) -> list[float]:
    return [
        float(value.replace("D", "E").replace("d", "e"))
        for value in NUMBER.findall(text)
    ]


def parse_vector(path: Path, declaration: str, expected: int) -> list[float]:
    lines = path.read_text(encoding="ascii").splitlines()
    start = next(
        i for i, line in enumerate(lines) if declaration.lower() in line.lower()
    )
    values: list[float] = []
    for line in lines[start + 1 :]:
        if len(line) >= 7 and not line[5].isspace():
            values.extend(numbers(line[6:]))
        if "/" in line:
            break
    if len(values) != expected:
        raise ValueError(
            f"{path}: expected {expected} values for {declaration}, found {len(values)}"
        )
    return values


def parse_phase(path: Path, variable: str) -> list[list[float]]:
    lines = path.read_text(encoding="ascii").splitlines()
    rows: list[list[float]] = []
    pattern = re.compile(rf"DATA\s*\(\({variable}\(i,j\)", re.IGNORECASE)
    for index, line in enumerate(lines):
        if not pattern.search(line):
            continue
        values: list[float] = []
        for continuation in lines[index + 1 :]:
            if len(continuation) >= 7 and not continuation[5].isspace():
                values.extend(numbers(continuation[6:]))
            if "/" in continuation:
                break
        if len(values) != 83:
            raise ValueError(
                f"{path}: expected 83 {variable} values, found {len(values)}"
            )
        rows.append(values)
    if len(rows) != 20:
        raise ValueError(f"{path}: expected 20 {variable} rows, found {len(rows)}")
    return rows


def format_vector(name: str, values: list[float]) -> str:
    body = ", ".join(f"{value:.7E}f" for value in values)
    return f"const float {name}[20] = {{{body}}};"


def format_matrix(name: str, rows: list[list[float]]) -> str:
    lines = [f"const float {name}[20][83] = {{"]
    for index, row in enumerate(rows):
        suffix = "," if index < len(rows) - 1 else ""
        lines.append(
            "    {" + ", ".join(f"{value:.7E}f" for value in row) + "}" + suffix
        )
    lines.append("};")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=Path, help="6SV2.1 source directory")
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(__file__).resolve().parents[1] / "src" / "aerosol_polar_tables.c",
    )
    args = parser.parse_args()

    declarations = []
    for component in COMPONENTS:
        path = args.source / f"{component.upper()}.f"
        declarations.append(
            format_matrix(f"aerosol_{component}_qha", parse_phase(path, "QHR"))
        )
        declarations.append(
            format_matrix(f"aerosol_{component}_uha", parse_phase(path, "UHR"))
        )

    bdm = args.source / "BDM.f"
    ext_sca = parse_vector(bdm, "data (ex_m(j),sc_m(j),j=1,20)", 40)
    declarations.extend(
        [
            format_vector("aerosol_bdm_ext", ext_sca[0::2]),
            format_vector("aerosol_bdm_sca", ext_sca[1::2]),
            format_vector(
                "aerosol_bdm_asy", parse_vector(bdm, "data (asy_m(j),j=1,20)", 20)
            ),
            format_matrix("aerosol_bdm_pha", parse_phase(bdm, "PHR")),
            format_matrix("aerosol_bdm_qha", parse_phase(bdm, "QHR")),
            format_matrix("aerosol_bdm_uha", parse_phase(bdm, "UHR")),
        ]
    )

    args.output.write_text(
        "/* Auto-generated by tools/extract_aerosol_polar_tables.py from 6SV2.1 Fortran source */\n"
        '#include "aerosol_tables.h"\n\n' + "\n\n".join(declarations) + "\n",
        encoding="ascii",
    )


if __name__ == "__main__":
    main()
