MODULE_TOPDIR = ../../..

PGM = r.dem.nk

LIBES = $(RASTERLIB) $(GISLIB) $(MATHLIB)
DEPENDENCIES = $(RASTERDEP) $(GISDEP)

SOURCES = \
	main.c

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd
