MODULE_TOPDIR = ../..

PGM = v.adehabitat.clusthr

LIBES = $(SITESLIB) $(VECTLIB) $(GISLIB) $(CURSES)
DEPENDENCIES= $(VECTDEP) $(GISDEP)
EXTRA_INC = $(VECT_INC)
EXTRA_CFLAGS = $(VECT_CFLAGS)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd
