---
name: General linting

on:
  push:
    branches:
      - grass[0-9]+
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress:
    # Do not cancel on protected branches, like grass8
    ${{ github.ref_protected != true }}

permissions: {}

jobs:
  super-linter:
    name: GitHub Super Linter
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      # To report GitHub Actions status checks
      statuses: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0
          persist-credentials: false
      - name: Lint code base
        uses: super-linter/super-linter@9e863354e3ff62e0727d37183162c4a88873df41 # v8.6.0
        env:
          ENABLE_GITHUB_ACTIONS_STEP_SUMMARY: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # By default, super-linter expect all linters to have their config
          # files inside .github/linters.
          # Setting it to the root of the repo for easier configuration here.
          LINTER_RULES_PATH: .
          FILTER_REGEX_EXCLUDE: ".*/src/gui/wxpython/wx.metadata/profiles/.*.xml"
          IGNORE_GENERATED_FILES: true
          VALIDATE_BASH: false # Until issues are fixed, some valid warnings
          VALIDATE_BIOME_FORMAT: false # Checked by biome in pre-commit, and with a different version
          VALIDATE_BIOME_LINT: false # Checked by biome in pre-commit, and with a different version
          VALIDATE_CHECKOV: false # Until issues are fixed
          VALIDATE_CLANG_FORMAT: false # Until we continue to check it in another workflow
          VALIDATE_CPP: false # Until a configuration file is created to not contradict clang-format
          VALIDATE_CSS: false # Using Biome instead of Stylelint
          VALIDATE_CSS_PRETTIER: false # Using Biome instead of Prettier
          VALIDATE_GITHUB_ACTIONS_ZIZMOR: false # Checked in pre-commit, and with a different version
          VALIDATE_GITLEAKS: false # Until configured to ignore g.parser key in main.c files
          VALIDATE_GRAPHQL_PRETTIER: false # Using Biome instead of Prettier
          VALIDATE_HTML: false # Until configured, some valid findings
          VALIDATE_HTML_PRETTIER: false # Until properly formatted
          VALIDATE_JAVASCRIPT_ES: false # Using Biome instead of ESLint
          VALIDATE_JAVASCRIPT_PRETTIER: false # Using Biome instead of Prettier
          VALIDATE_JSCPD: false # Too many detections, should be enabled only for changed files
          VALIDATE_JSON: false # Using Biome instead of ESLint
          VALIDATE_JSONC: false # Using Biome instead of ESLint
          VALIDATE_JSONC_PRETTIER: false # Using Biome instead of Prettier
          VALIDATE_JSON_PRETTIER: false # Using Biome instead of Prettier
          VALIDATE_JSX: false # Using Biome instead of ESLint
          VALIDATE_JSX_PRETTIER: false # Using Biome instead of Prettier
          VALIDATE_JUPYTER_NBQA_BLACK: false # Handled by our ruff formatting
          VALIDATE_JUPYTER_NBQA_ISORT: false # Until fixed and confirmed safe
          VALIDATE_JUPYTER_NBQA_MYPY: false # Until fixed
          VALIDATE_JUPYTER_NBQA_PYLINT: false # Until fixed
          VALIDATE_JUPYTER_NBQA_RUFF: false # ruff version isn't updated at the same time as we do
          VALIDATE_LATEX: false # Until issues are fixed, some valid findings
          VALIDATE_MARKDOWN_PRETTIER: false # Until issues are fixed
          VALIDATE_NATURAL_LANGUAGE: false # Until issues are fixed, lots of valid suggestions
          VALIDATE_PERL: false # Until issues are fixed
          VALIDATE_PYTHON_BLACK: false # We are using ruff format
          VALIDATE_PYTHON_FLAKE8: false
          VALIDATE_PYTHON_ISORT: false # Until issues are fixed
          VALIDATE_PYTHON_MYPY: false # Issue with module name wx.wms
          VALIDATE_PYTHON_PYLINT: false # Until issues are fixed
          VALIDATE_PYTHON_RUFF: false # Until we continue to check it in another workflow
          VALIDATE_PYTHON_RUFF_FORMAT: false # Until we continue to check it in another workflow
          VALIDATE_R: false
          VALIDATE_RENOVATE: false # Until configuration file is upgraded
          VALIDATE_SHELL_SHFMT: false # Until reformatting failing files
          VALIDATE_SPELL_CODESPELL: false # Until typos are fixed or excluded
          VALIDATE_TSX: false # Using Biome instead of ESLint
          VALIDATE_TYPESCRIPT_ES: false # Using Biome instead of ESLint
          VALIDATE_TYPESCRIPT_PRETTIER: false # Using Biome instead of Prettier
          VALIDATE_VUE: false # Using Biome instead of ESLint
          VALIDATE_VUE_PRETTIER: false # Using Biome instead of Prettier
          GITHUB_ACTIONS_ZIZMOR_CONFIG_FILE: zizmor.yml
          MARKDOWN_CONFIG_FILE: .markdownlint.yml
          PYTHON_RUFF_CONFIG_FILE: pyproject.toml
          PYTHON_RUFF_FORMAT_CONFIG_FILE: pyproject.toml
          YAML_CONFIG_FILE: .yamllint
